
<?php
if (isset($this->form)) {
	$_f = $this->form;
	$attribs = $_f->getAttribs();
	?>
<div class="page_head">
    <h3><?php echo "Edit ".str_replace("_"," ",$_f->getName()); ?></h3>
</div>
<br/>
<form <?php foreach($attribs as $key=>$value) { echo "$key='$value' "; } ?>>
	<?php
    $groups = $_f->getDisplayGroups();
    foreach($groups as $group) {
    ?>
		<fieldset class="<?php echo $group->getAttrib('class'); ?>">
			<legend><?php echo ucwords($group->getLegend()); ?></legend>
			<div section="<?=$group->getAttrib('id');?>">
	            <?php
	            $elements = $group->getElements();
	            foreach($elements as $element) { ?>
	               <div section='<?=$element->getName()?>'>

		 	           <?php echo $element->render(); ?>
		               <div class="clear"></div>
		           </div>
	            <?php } ?>
	        </div>
        </fieldset>
    <?php }?>
    <br/>
</form>
    <div class='back_button' onclick='history.go(-1)'>Back</div>
    <div class="save_button" onclick='$j("#menu_form").submit()'>Save</div>
<?php } ?>

