<?php $races = $this->races; ?>
<div id='user_admin'>
	Click on a race to view it. You can also search for races using the search box to the right.<br />
    <?php if (Bootstrap::isInGroup('administrator')) { ?>If you would like to add a race, click on the Add a race link.<?php } ?><br /><br />
	<form id='form_validate' action='/admin/users/' method='get'>
       	<label for='q'>Search for a race</label>
    	<input id='q' name='q' type='text' value='<?=$this->q?>' />
    <div class='clear'></div>
       	<div class='search_button' onclick='$j("#form_validate").submit()'>&nbsp</div>
    </form>
    <div class='clear'></div>
	<?=$this->paginationControl($races, 'Sliding', 'pagination.phtml')?>
    <table id='list'>
    	<tr>
            <th>Race Name</th>
            <th>Required Level</th>
            <th>Max Level</th>
        </tr>
        <?php foreach($races as $race) { ?>
        <tr id='admin_user' onclick="window.location.href='/wcs/view/id/<?=$race->id?>'">
            <td><?=$race->name?></td>
			<td><?=$race->req_level?></td>
			<td><?=$race->max_level?></td>
        </tr>
        <?php } ?>
	</table>
</div>

    <div class='clear'></div>
<?php if (Bootstrap::isInGroup('administrator')) { ?><div class='adduser_button' onclick='window.location.href="/wcs/add"'>Add a race</div><?php } ?>