<?php $race = $this->race; ?>
<div id='wcs_race'>
	<a href='/wcs'>Click here to go back to the search.</a><br />
    <?php if (Bootstrap::isInGroup('administrator')) { ?><a href='/wcs/edit/id/<?=$race->id;?>'>Edit</a><?php } ?><br /><br />
	<h2><?=$race->name;?></h2>
    <table id='wcs_table'>
	<tr>
    	<td>Required Level:</td>
        <td><?=$race->req_level;?></td>
    </tr>
    <tr><td></td></tr>
	<tr>
    	<td>Max Level:</td>
        <td><?=$race->max_level;?></td>
    </tr>
    <tr><td></td></tr>
	<?php if(!empty($race->skill_1_name)) { ?>
        <tr class='skill'>
            <td>Skill 1: </td>
            <td><?=$race->skill_1_name;?></td>
            <td><?=$race->skill_1_level;?> level(s)</td>
        </tr>
        <tr class='skill'>
            <td colspan=3><?=$race->skill_1_notes;?></td></td>
        </tr>
    <?php } ?>
    <tr><td></td></tr>
	<?php if(!empty($race->skill_2_name)) { ?>
        <tr class='skill'>
            <td>Skill 2: </td>
            <td><?=$race->skill_2_name;?></td>
            <td><?=$race->skill_2_level;?> level(s)</td>
        </tr>
        <tr class='skill'>
            <td colspan=3><?=$race->skill_2_notes;?></td></td>
        </tr>
    <?php } ?>
    <tr><td></td></tr>
	<?php if(!empty($race->skill_3_name)) { ?>
        <tr class='skill'>
            <td>Skill 3: </td>
            <td><?=$race->skill_3_name;?></td>
            <td><?=$race->skill_3_level;?> level(s)</td>
        </tr>
        <tr class='skill'>
            <td colspan=3><?=$race->skill_3_notes;?></td></td>
        </tr>
    <?php } ?>
    <tr><td></td></tr>
	<?php if(!empty($race->skill_4_name)) { ?>
        <tr class='skill'>
            <td>Skill 4: </td>
            <td><?=$race->skill_4_name;?></td>
            <td><?=$race->skill_4_level;?> level(s)</td>
        </tr>
        <tr class='skill'>
            <td colspan=3><?=$race->skill_4_notes;?></td></td>
        </tr>
    <?php } ?>
    <tr><td></td></tr>
	<?php if(!empty($race->skill_5_name)) { ?>
        <tr class='skill'>
            <td>Skill 5: </td>
            <td><?=$race->skill_5_name;?></td>
            <td><?=$race->skill_5_level;?> level(s)</td>
        </tr>
        <tr class='skill'>
            <td colspan=3><?=$race->skill_5_notes;?></td></td>
        </tr>
    <?php } ?>
    <tr><td></td></tr>
	<?php if(!empty($race->skill_6_name)) { ?>
        <tr class='skill'>
            <td>Skill 6: </td>
            <td><?=$race->skill_6_name;?></td>
            <td><?=$race->skill_6_level;?> level(s)</td>
        </tr>
        <tr class='skill'>
            <td><?=$race->skill_6_notes;?></td></td>
        </tr>
    <?php } ?>
    <tr><td></td></tr>
	<?php if(!empty($race->skill_7_name)) { ?>
        <tr class='skill'>
            <td>Skill 7: </td>
            <td><?=$race->skill_7_name;?></td>
            <td><?=$race->skill_7_level;?> level(s)</td>
        </tr>
        <tr class='skill'>
            <td><?=$race->skill_7_notes;?></td></td>
        </tr>
    <?php } ?>
    <tr><td></td></tr>
	<?php if(!empty($race->skill_8_name)) { ?>
        <tr class='skill'>
            <td>Skill 8: </td>
            <td><?=$race->skill_8_name;?></td>
            <td><?=$race->skill_8_level;?> level(s)</td>
        </tr>
        <tr class='skill'>
            <td><?=$race->skill_8_notes;?></td></td>
        </tr>
    <?php } ?>
    <tr><td></td></tr>
	<?php if(!empty($race->skill_9_name)) { ?>
        <tr class='skill'>
            <td>Skill 9: </td>
            <td><?=$race->skill_9_name;?></td>
            <td><?=$race->skill_9_level;?> level(s)</td>
        </tr>
        <tr class='skill'>
            <td><?=$race->skill_9_notes;?></td></td>
        </tr>
    <?php } ?>
    <tr><td></td></tr>
	<?php if(!empty($race->skill_10_name)) { ?>
        <tr class='skill'>
            <td>Skill 10: </td>
            <td><?=$race->skill_10_name;?></td>
            <td><?=$race->skill_10_level;?> level(s)</td>
        </tr>
        <tr class='skill'>
            <td><?=$race->skill_10_notes;?></td></td>
        </tr>
    <?php } ?>
    <tr><td></td></tr>
    </table>
    <div class='clear'></div>
	
</div>
