<div class="faqWrap">
<?php if(Bootstrap::isInGroup('administrator')) { ?>
<div class="faqAdmin"><a href="/faq/new/">New F.A.Q Item</a><div class="hr"><hr/></div></div>
<?php } ?>
		<ol>
<?php
	$faq = $this->data;
	foreach($faq as $item) {
		$id = $item->id;
		$title = $item->faq_title;
		$content = $item->faq_content;
		$link;
		$onclick = "onclick='\$(\"#faq_$id\").toggle()'";
		if(Bootstrap::isInGroup('administrator')) {
			$link = "<a style='font-weight:normal;font-size:.8em; padding-left:15px;' href='/faq/edit/id/$id'>Edit F.A.Q</a>";
		}
		?><div class="faq_item">
			<li><div class="title"><a href="#" <?=$onclick?> ><?=$title?></a><?=$link?></div></li>
			<div id="faq_<?=$id?>" class="content" style="display:none;">
				<div class="hr"><hr/></div>
				<?=$content?>
			</div>
		</div>
	<?php
	}
	?></ol>
</div>