<?php 
$brow = strtolower(BROWSER);
$ver = BROWSERV; 
$menu = ROOT_DIR.'/includes/static/menu.php';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="CACHE-CONTROL" content="PUBLIC" />
		<meta http-equiv="EXPIRES" content="<?=date('r',time()+60*60*7);?>" />
		<meta name="keywords" content="<?=$this->metaKeywords?>" />
		<meta name="description" content="<?=$this->metaDescription?>" />
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<meta name="robots" content="all">
		<title>Seductive Turtle</title>
		<link href="/css/reset" rel="stylesheet" type="text/css" media="screen" />
		<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css' />
		<link href='http://fonts.googleapis.com/css?family=Nobile' rel='stylesheet' type='text/css' />
		<link href="/css/layout" rel="stylesheet" type="text/css" media="screen" />
		<?php if(!empty($this->page)) { ?>
		<link href="/css/<?=$this->page?>" rel="stylesheet" type="text/css" media="screen" />
		<?php } ?>
		<link href="/css/custom" rel="stylesheet" type="text/css" media="screen" />
		<link rel="stylesheet" href="/includes/css/nivo-default.css" type="text/css" media="screen" />
		<link rel="stylesheet" href="/includes/css/nivo-slider.css" type="text/css" media="screen" />
		<link rel="stylesheet" href="/includes/css/prettyPhoto.css" type="text/css" media="screen" />
		<script type="text/javascript" src="http://www.google.com/jsapi"></script>
		<script type="text/javascript">
			google.load("jquery", "1");
			google.load("jqueryui", "1");
			<?php if($this->admin) echo "google.load('visualization', '1', {packages: ['annotatedtimeline']});" ?> 
		</script>
		<script type='text/javascript'>
		function addLoadEvent(func) {
		  var oldonload = window.onload;
		  if (typeof window.onload != 'function') {
			window.onload = func;
		  } else {
			window.onload = function() {
			  if (oldonload) {
				oldonload();
			  }
			  func();
			}
		  }
		}
		</script>
	</head>


	<body>
		<?php 
		/* if(!in_array($brow,array('firefox','chrome','safari')) ) { ?>
			<div id='browser'>This site is best viewed in Firefox, Chrome, and Safari.</div>
		<?php } elseif ($brow == 'firefox' && $ver <= 350) { ?> 
			<div id='browser'>This site is best viewed in Firefox version 3.5 or better.</div>
		<?php } elseif ($brow == 'safari' && $ver <= 5000) { ?>
			<div id='browser'>This site is best viewed in Safari version 3 or better.</div>
		<?php }  */
		?>
		<!-- MAIN WRAPPER -->
		<div class="main-wrapper">
		<!-- MAIN CONTAINER -->
		<div class="container">
			<!-- HEADER -->
			<div class="span-6 notopmargin">
			<span class="logo seductive">seductive</span><span class="logo turtle">Turtle</a>
		    </div>
		    <div class="span-18 notopmargin last">
			<ul class="sf-menu">
				<?php include_once $menu; ?>
			</ul>
		    </div>
		    <div class="span-24 separator"></div>
		    <!-- END HEADER -->
		    <!-- MAIN CONTENT -->
			<?php echo $this->layout()->content; ?>
			<div class="span-24 separator-double"></div>
			<div class="span-24 footer">
				<div class="span-6 notopmargin">
				<a href="/"><span class="logo seductive">Seductive</span><br /><br /><span class="logo turtle">Turtle</span></a>
			    </div>
			    <div class="span-6 notopmargin">
				<div class="icon-white-big icon47-white left"></div>
				<span class="seductive">Seductive</span> <span class="turtle">Turtle</span>
				<p class="small">Dedicated to Open Source and Cutting Edge development</p>
				<p class="small em">We have, what you need</p>
			    </div>
			    <div class="span-6 tweets small notopmargin">
				<div class="icon-white-big icon101-white left"></div>
				<h6>Recent tweets</h6>
				<p class="small"></p>
				<p class="small em"></p>
			    </div>
			    <div class="span-6 notopmargin last">
				<div class="icon-white-big icon193-white left"></div>
				<h6>Contact info</h6>
				<p class="small">San Diego, Ca<br/> Phone: <span class="strong">612.669.0287</span></p>
							<div class="span-6 notopmargin last"><span class="strong em left">Follow us on:</span></div>
				<div class="tweet-icon">
				    <a target="new tab above" href="http://www.twitter.com/seductiveturtle" class='social' title='Twitter'><img src="/includes/images/1px.png" alt="" width="26px" height="26px" /></a>
				</div>
				<div class="facebook-icon">
				    <a target="new tab above" href="http://www.facebook.com/seductive.turtle.inc" class='social' title='Facebook'><img src="/includes/images/1px.png" alt="" width="26px" height="26px" /></a>
				</div>
				<div class="google-icon">
				    <a target="new tab above" href="https://plus.google.com/u/0/107488175994880166077" class='social' title='Google +'><img src="/includes/images/1px.png" alt="" width="26px" height="26px" /></a>
				</div>
			    </div>
			</div>
		    </div>
		    <!-- END MAIN CONTENT -->
		    <div class="clear"></div>
		</div>
		<!-- END MAIN CONTAINER -->
		</div>
		<!-- END MAIN WRAPPER -->
		<script type="text/javascript">
		$(document).ready(function() {
			try {
				var pageTracker = _gat._getTracker("UA-15082163-1");
				pageTracker._trackPageview();
			} catch(err) {}
		});
		</script>
		<script type="text/javascript" src="/includes/js/custom.js"></script>
		<script type="text/javascript" src="/includes/js/slides.min.jquery.js"></script>
		<script type="text/javascript" src="/includes/js/nivo-slider/jquery.nivo.slider.pack.js"></script>
		<script type="text/javascript" src="/includes/js/superfish-menu/hoverIntent.js"></script>
		<script type="text/javascript" src="/includes/js/superfish-menu/superfish.js"></script>
		<script type="text/javascript" src="/includes/js/scrolltop/scrolltopcontrol.js"></script>
		<script type="text/javascript" src="/includes/js/prettyPhoto/jquery.prettyPhoto.js"></script>
		<script type="text/javascript" src="/includes/js/jquery.featureList-1.0.0.js"></script>
		<script type="text/javascript" src="/includes/js/swfobject/swfobject.js"></script>
		<script type="text/javascript" src="/includes/js/easing/jquery.easing.1.3.js"></script>
		<script type="text/javascript" src="/includes/js/jquery.iconmenu.js"></script>
		<script type="text/javascript" src="/includes/js/kwicks/jquery.kwicks-1.5.1.pack.js"></script>
		<script type="text/javascript" src="/includes/js/mosaic/mosaic.1.0.1.js"></script>
		<script type="text/javascript" src="/includes/js/jquery.tipsy.js"></script>
		<script type="text/javascript" src="/includes/js/jquery.quicksand.js"></script>
		<script type="text/javascript" src="/includes/js/jquery.tablesorter.js"></script>
		<?php if($this->ck) { ?>
		<script type="text/javascript" src="/includes/ckeditor/ckeditor.js"></script>
		<script type='text/javascript'>
			CKEDITOR.baseHref = 'http://<?=Bootstrap::getConfig("site","url")?>';
			CKEDITOR.config.bodyId= 'content';
			CKEDITOR.config.contentsCss= '/css/layout';
			CKEDITOR.replace('ck_replace',
			 {
				height:"200", width:"720"
			 });
		</script>
		<?php } ?>
	</body>
</html>
