<div class="slogan">
	<div class="span-24">
		<h2>Welcome to "<a class="link" href="">METRIC</a>", clean and simple HTML / CSS template</h2>
		<h4 class="em">Please feel free to browse our <a class="link" href="services.html">services</a>, enjoy and please leave comments</h4>
	</div>
	<div class="span-24 separator"></div>
</div>
<div class="span-24 service">
	<div class="span-12 notopmargin">
		<div class="big-rounded-icon-white left">
			<div class="icon-white-big icon95-white"></div>
		</div>
		<div class="span-10 notopmargin last">
			<h3><a href="services.html" class="service-tipsy north" title='Web sites from 999.99$'>Internet marketing</a></h3>
			<p>Nam euismod auctor lectus in sodales. Fusce sed justo est. Ut dapibus adipiscing turpis, luctus scelerisque massa pellentesque.</p>
			<a class="button_readmore"  href="services.html">Read more</a>
		</div>
	</div>
	<div class="span-12 notopmargin last">
		<div class="big-rounded-icon-white left">
			<div class="icon-white-big icon234-white"></div>
		</div>
		<div class="span-10 notopmargin last">
			<h3><a href="services.html" class="service-tipsy north" title='Print design from 199.99$'>Outdoor services</a></h3>
			<p>Nam euismod auctor lectus in sodales. Fusce sed justo est. Ut dapib us adipiscing turpis, luctus scelerisque massa pellentesque.</p>
			<a class="button_readmore"  href="services.html">Read more</a>
		</div>
	</div>
</div>
<div class="span-24 separator"></div>
<div class="span-24">
	<ul id="sti-menu" class="sti-menu">
		<li data-hovercolor="#ffffff">
			<a href="#">
				<h2 data-type="mText" class="sti-item">Saving</h2>
				<h3 data-type="sText" class="sti-item">Save upt to 50% NOW!</h3>
				<span data-type="icon" class="sti-icon sti-icon-piggy sti-item"></span>
			</a>
		</li>
		<li data-hovercolor="#ffffff">
			<a href="#">
				<h2 data-type="mText" class="sti-item">Servicing</h2>
				<h3 data-type="sText" class="sti-item">Some subtitle goes here</h3>
				<span data-type="icon" class="sti-icon sti-icon-service sti-item"></span>
			</a>
		</li>
		<li class="last" data-hovercolor="#ffffff">
			<a href="#">
				<h2 data-type="mText" class="sti-item">Support</h2>
				<h3 data-type="sText" class="sti-item">And one more subtitle here</h3>
				<span data-type="icon" class="sti-icon sti-icon-support sti-item"></span>
			</a>
		</li>
	</ul>
</div>
<div class="span-24 separator"></div>
<div class="span-24 notopmargin">
	<div class="span-24 from_portfolio">
		<div class="span-24 notopmargin">
			<div class="span-6 notopmargin">
				<h5><a class="link" href="portfolio-details.html">Some project title</a></h5>
				<p>Vivamus volutpat euismod ullamco rper, sed sit amet nulla et ligula consequat</p>
				<a class="button_readmore"  href="portfolio-details.html">Read more</a>
			</div>
			<div class="span-6 notopmargin">
				<h5><a class="link" href="portfolio-details.html">Another work</a></h5>
				<p>Sed sit amet nulla et ligula consequat, vivamus volutpat euismod ullamco rper.</p>
				<a class="button_readmore"  href="portfolio-details.html">Read more</a>
			</div>
			<div class="span-6 notopmargin">
				<h5><a class="link" href="portfolio-details.html">Special work</a></h5>
				<p>Mauris quam tortor, conval eu tincid, nulla ullamcorper, neque sodales el.</p>
				<a class="button_readmore"  href="portfolio-details.html">Read more</a>
			</div>
			<div class="span-6 notopmargin last">
				<h5><a class="link" href="portfolio-details.html">And another</a></h5>
				<p>Nulla ullamcorper, neque sodales el, mauris quam tortor, conval eu tincid.</p>
				<a class="button_readmore"  href="portfolio-details.html">Read more</a>
			</div>
		</div>
	</div>
</div>
