<?php
header('Content-type: text/css');
$colors = Bootstrap::getDataM('template');
$body = array();
$header = array();
$content = array();
$footer = array();
foreach($colors as $color) {
	if($color->template_section == 'body') {
		if($color->template_name == 'background')
			$body['background'] = stripslashes($color->template_current_value);
		if($color->template_name == 'color')
			$body['color'] = stripslashes($color->template_current_value);
		if($color->template_name == 'a')
			$body['link'] = stripslashes($color->template_current_value);
		if($color->template_name == 'a:hover')
			$body['link_hover'] = stripslashes($color->template_current_value);
		if($color->template_name == 'font')
			$body['font'] = stripslashes($color->template_current_value);
	}
	if($color->template_section == 'header') {
		if($color->template_name == 'color')
			$header['color'] = stripslashes($color->template_current_value);
		if($color->template_name == 'a')
			$header['link'] = stripslashes($color->template_current_value);
		if($color->template_name == 'a:hover')
			$header['link_hover'] = stripslashes($color->template_current_value);
	}
	if($color->template_section == 'content') {
		if($color->template_name == 'background')
			$content['background'] = stripslashes($color->template_current_value);
		if($color->template_name == 'color')
			$content['color'] = stripslashes($color->template_current_value);
		if($color->template_name == 'a')
			$content['link'] = stripslashes($color->template_current_value);
		if($color->template_name == 'a:hover')
			$content['link_hover'] = stripslashes($color->template_current_value);
		if($color->template_name == 'header')
			$content['header'] = stripslashes($color->template_current_value);
	}
	if($color->template_section == 'footer') {
		if($color->template_name == 'background')
			$footer['background'] = stripslashes($color->template_current_value);
		if($color->template_name == 'color')
			$footer['color'] = stripslashes($color->template_current_value);
		if($color->template_name == 'a')
			$footer['link'] = stripslashes($color->template_current_value);
		if($color->template_name == 'a:hover')
			$footer['link_hover'] = stripslashes($color->template_current_value);
	}
}
?>
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
	text-decoration: none;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
a{ color:inherit;}

/*
METRIC - CSS
Copyrights - orange-idea.com
Creator: Orangeidea
October - 2011
Portfolio - http://themeforest.net/user/OrangeIdea/portfolio

/*-------------------------------------------------------*/
	/*BODY*/
/*-------------------------------------------------------*/

body {
	background-color:#292929;
	background-image:url('/includes/images/pattern/body-bg-2.png');
	background-repeat:repeat;
	text-shadow: none;
	font-family: Arial, Helvetica, sans-serif;
	color:#666666;
	font-size:12px;
	line-height:1.5em;
}

*[onclick] { cursor: pointer; }

/*-------------------------------------------------------*/
	/*Logo*/
/*-------------------------------------------------------*/
.logo { font-size: 4em; font-family: Yanone Kaffeesatz; }
.logo.seductive { color: black; }
.logo.turtle { color: #800; }


/*-------------------------------------------------------*/
	/*Typography*/
/*-------------------------------------------------------*/
h1, h2, h3, h4, h5, h6 {
	font-family:Yanone Kaffeesatz;
	color:#000000; }
h1 a, h2 a, h3 a, h4 a, h5 a, h6 a { font-weight: inherit; }
h1 { font-size: 36px; line-height: 50px; margin-bottom: 10px;}
h2 { font-size: 32px; line-height: 40px; margin-bottom: 10px; }
h3 { font-size: 26px; line-height: 23px; margin-bottom: 8px; }
h4 { font-size: 22px; line-height: 30px; margin-bottom: 4px; }
h5 { font-size: 16px; line-height: 24px; margin-bottom: 4px; }
h6 { font-size: 14px; line-height: 21px; }

p { margin: 0 0 20px 0; }
.small { font-size:90%;}
p img { margin: 0; }
p.lead { font-size: 21px; line-height: 27px; color: #777;  }
.em { font-style: italic; color:#777777; margin-top:3px; }
.strong { font-weight: bold; color: #333; }
.small-italic {font-size:90%; font-style:italic;}
hr { border: solid #ddd; border-width: 1px 0 0; clear: both; margin: 10px 0 30px; height: 0; }
/*404error*/
p.error{
	font-size:172px;
	font-family:Arial;
	margin-bottom:40px;
	margin-top:60px;
	padding-right:20px;

}
.center { text-align:center;}
.slogan { text-align:center;}
.slogan h2 { margin-bottom:0px; text-transform:uppercase;}
.slogan h4 { margin-bottom:0px; text-transform:none;}
.footer h6{ text-transform:uppercase; margin-bottom:8px; font-size:18px;}
.from_portfolio h3 { margin-bottom:20px !important;}
.footer p { padding-right:10px; width:210px; margin-bottom:5px !important;}
.colored { color:<?=$content['link']?>;}

.link { color:<?=$content['link']?>;}
.link:hover { text-decoration: underline; cursor:pointer;}
a:hover { text-decoration:underline;}
.footer {}

/*-------------------------------------------------------*/
	/*GRID*/
/*-------------------------------------------------------*/

.main-wrapper {
	width: 1030px;
	margin: 0 auto;
	background:url('/includes/images/pattern/2.png');
	margin-top:30px;
	margin-bottom:30px;
	padding-top:20px;
	padding-bottom:20px;
	border-radius: 10px;
	-webkit-border-radius: 10px;
	-moz-border-radius: 10px;
}

/* A container should group all your columns. */
.container {
	width: 940px;
	margin: 0 auto;
	padding:30px 20px 30px 30px;
	background-color:#f9f9f9;
	background-image:url('/includes/images/pattern/2w.png');
	border-radius: 10px;
	-webkit-border-radius: 10px;
	-moz-border-radius: 10px;
	min-height:500px;
}

/* Columns
-------------------------------------------------------------- */

/* Sets up basic grid floating and margin. */
div.span-1, div.span-2, div.span-3, div.span-4, div.span-5, div.span-6, div.span-7, div.span-8, div.span-9, div.span-10, div.span-11, div.span-12, div.span-13, div.span-14, div.span-15, div.span-16, div.span-17, div.span-18, div.span-19, div.span-20, div.span-21, div.span-22, div.span-23, div.span-24 {float:left; margin-right: 20px; margin-top:40px;}
.columns .span-1, .columns .span-2, .columns .span-3, .columns .span-4, .columns .span-5, .columns .span-6, .columns .span-7, .columns .span-8, .columns .span-9, .columns .span-10, .columns .span-11, .columns .span-12, .columns .span-13, .columns .span-14, .columns .span-15, .columns .span-16, .columns .span-17, .columns .span-18, .columns .span-19, .columns .span-20, .columns .span-21, .columns .span-22, .columns .span-23, .columns .span-24 { height:30px; background:#ededed; text-align:center; margin-top:10px !important; padding-top:10px;}
p.span-1, p.span-2, p.span-3, p.span-4, p.span-5, p.span-6, p.span-7, p.span-8, p.span-9, p.span-10, p.span-11, p.span-12, p.span-13, p.span-14, p.span-15, p.span-16, p.span-17, p.span-18, p.span-19, p.span-20, p.span-21, p.span-22, p.span-23, p.span-24 {float:left; margin-right: 20px; margin-top:40px;}
/* The last column in a row needs this class. */
div.last { margin-right: 0; }

/* Use these classes to set the width of a column. */
.span-1  { width: 20px;}
.span-2  { width: 60px;}
.span-3  { width: 100px;}
.span-4  { width: 140px;}
.span-5  { width: 180px;}
.span-6  { width: 220px;}
.span-7  { width: 260px;}
.span-8  { width: 300px;}
.span-9  { width: 340px;}
.span-10 { width: 380px;}
.span-11 { width: 420px;}
.span-12 { width: 460px;}
.span-13 { width: 500px;}
.span-14 { width: 540px;}
.span-15 { width: 580px;}
.span-16 { width: 620px;}
.span-17 { width: 660px;}
.span-18 { width: 700px;}
.span-19 { width: 740px;}
.span-20 { width: 780px;}
.span-21 { width: 820px;}
.span-22 { width: 860px;}
.span-23 { width: 900px;}
.span-24, div.span-24 { width: 940px; }


/* Add these to a column to append empty cols. */
.append-1  { padding-right: 40px;}
.append-2  { padding-right: 80px;}
.append-3  { padding-right: 120px;}
.append-4  { padding-right: 160px;}
.append-5  { padding-right: 200px;}
.append-6  { padding-right: 240px;}
.append-7  { padding-right: 280px;}
.append-8  { padding-right: 320px;}
.append-9  { padding-right: 360px;}
.append-10 { padding-right: 400px;}
.append-11 { padding-right: 440px;}
.append-12 { padding-right: 480px;}
.append-13 { padding-right: 520px;}
.append-14 { padding-right: 560px;}
.append-15 { padding-right: 600px;}
.append-16 { padding-right: 640px;}
.append-17 { padding-right: 680px;}
.append-18 { padding-right: 720px;}
.append-19 { padding-right: 760px;}
.append-20 { padding-right: 800px;}
.append-21 { padding-right: 840px;}
.append-22 { padding-right: 880px;}
.append-23 { padding-right: 920px;}


/* Add these to a column to prepend empty cols. */
.prepend-1  { padding-left: 40px;}
.prepend-2  { padding-left: 80px;}
.prepend-3  { padding-left: 120px;}
.prepend-4  { padding-left: 160px;}
.prepend-5  { padding-left: 200px;}
.prepend-6  { padding-left: 240px;}
.prepend-7  { padding-left: 280px;}
.prepend-8  { padding-left: 320px;}
.prepend-9  { padding-left: 360px;}
.prepend-10 { padding-left: 400px;}
.prepend-11 { padding-left: 440px;}
.prepend-12 { padding-left: 480px;}
.prepend-13 { padding-left: 520px;}
.prepend-14 { padding-left: 560px;}
.prepend-15 { padding-left: 600px;}
.prepend-16 { padding-left: 640px;}
.prepend-17 { padding-left: 680px;}
.prepend-18 { padding-left: 720px;}
.prepend-19 { padding-left: 760px;}
.prepend-20 { padding-left: 800px;}
.prepend-21 { padding-left: 840px;}
.prepend-22 { padding-left: 880px;}
.prepend-23 { padding-left: 920px;}



/* Border on right hand side of a column. */
div.border {
  padding-right:9px;
  margin-right:10px;
  border-right: 1px solid #eee;
}

/* Border with more whitespace, spans one column. */
div.colborder {
  padding-right:13px;
  margin-right:10px;
  border-right: 1px solid #eee;
}

/* Use these classes on an element to push it into the 
   next column, or to pull it into the previous column.  */

.pull-1 { margin-left: -40px;}
.pull-2 { margin-left: -80px;}
.pull-3 { margin-left: -120px;}
.pull-4 { margin-left: -160px;}
.pull-5 { margin-left: -200px;}
.pull-6 { margin-left: -240px;}
.pull-7 { margin-left: -280px;}
.pull-8 { margin-left: -320px;}
.pull-9 { margin-left: -360px;}
.pull-10 { margin-left: -400px;}
.pull-11 { margin-left: -440px;}
.pull-12 { margin-left: -480px;}
.pull-13 { margin-left: -520px;}
.pull-14 { margin-left: -560px;}
.pull-15 { margin-left: -600px;}
.pull-16 { margin-left: -640px;}
.pull-17 { margin-left: -680px;}
.pull-18 { margin-left: -720px;}
.pull-19 { margin-left: -760px;}
.pull-20 { margin-left: -800px;}
.pull-21 { margin-left: -840px;}
.pull-22 { margin-left: -880px;}
.pull-23 { margin-left: -920px;}
.pull-24 { margin-left: -960px;}

.pull-1, .pull-2, .pull-3, .pull-4, .pull-5, .pull-6, .pull-7, .pull-8, .pull-9, .pull-10, .pull-11, .pull-12, .pull-13, .pull-14, .pull-15, .pull-16, .pull-17, .pull-18, .pull-19, .pull-20, .pull-21, .pull-22, .pull-23, .pull-24 {float:left;position:relative;}


.push-1 { margin: 0 -40px 1.5em 40px;}
.push-2 { margin: 0 -80px 1.5em 80px;}
.push-3 { margin: 0 -120px 1.5em 120px;}
.push-4 { margin: 0 -160px 1.5em 160px;}
.push-5 { margin: 0 -200px 1.5em 200px;}
.push-6 { margin: 0 -240px 1.5em 240px;}
.push-7 { margin: 0 -280px 1.5em 280px;}
.push-8 { margin: 0 -320px 1.5em 320px;}
.push-9 { margin: 0 -360px 1.5em 360px;}
.push-10 { margin: 0 -400px 1.5em 400px;}
.push-11 { margin: 0 -440px 1.5em 440px;}
.push-12 { margin: 0 -480px 1.5em 480px;}
.push-13 { margin: 0 -520px 1.5em 520px;}
.push-14 { margin: 0 -560px 1.5em 560px;}
.push-15 { margin: 0 -600px 1.5em 600px;}
.push-16 { margin: 0 -640px 1.5em 640px;}
.push-17 { margin: 0 -680px 1.5em 680px;}
.push-18 { margin: 0 -720px 1.5em 720px;}
.push-19 { margin: 0 -760px 1.5em 760px;}
.push-20 { margin: 0 -800px 1.5em 800px;}
.push-21 { margin: 0 -840px 1.5em 840px;}
.push-22 { margin: 0 -880px 1.5em 880px;}
.push-23 { margin: 0 -920px 1.5em 920px;}
.push-24 { margin: 0 -960px 1.5em 960px;}

.push-1, .push-2, .push-3, .push-4, .push-5, .push-6, .push-7, .push-8, .push-9, .push-10, .push-11, .push-12, .push-13, .push-14, .push-15, .push-16, .push-17, .push-18, .push-19, .push-20, .push-21, .push-22, .push-23, .push-24 {float:right;position:relative; margin-top:10px !important; margin-bottom:0px}

.notopmargin { margin-top:0px !important;}
.nobottommargin { margin-bottom:0px !important;}
.last { margin-right:0px !important;}
.left {float:left}
.right {float:right}


/* Misc classes and elements
-------------------------------------------------------------- */

/* Use a .box to create a padded box inside a column.  */ 
.box { 
	padding: 1.5em; 
	margin-bottom: 1.5em; 
	background: #E5ECF9; 
}

.separator {
	clear:both;
	margin-top:40px;
	height:1px;
	background:#ededed;
}
.separator-inner {
	clear:both;
	margin-top:15px !important;
	height:1px;
	background:#ededed;
}
.separator-double {
	clear:both;
	margin-top:40px;
	height:10px;
	background:#ffffff;
	background-image:url('/includes/images/pattern/1.png');
}
.slogan .span-24 { margin-top:20px;}
/* Clearing floats without extra markup
   Based on How To Clear Floats Without Structural Markup by PiE
   [http://www.positioniseverything.net/easyclearing.html] */

.clearfix:after, .container:after {
	content: "."; 
	display: block; 
	height: 0; 
	clear: both; 
	visibility: hidden;
}
.clearfix, .container {display: inline-block;}
* html .clearfix,
* html .container {height: 1%;}
.clearfix, .container {display: block;}

/* Regular clearing
   apply to column that should drop below previous ones. */

.clear { clear:both; }


/*****Navigation Basic Layout*****/
ul#filter { float: left; list-style: none; margin-left: 0; width: 100%; }
ul#filter li {
	float: left;
	font-size:10px;
	line-height: 12px;
	margin-right:15px;
	padding: 2px 8px;
	background:#ffffff;
	border: 1px solid #ededed;
	border-radius: 3px;
	-webkit-border-radius: 3px;
	-moz-border-radius: 3px;
}
ul#filter li:first-child { margin-left:10px; }
ul#filter a { text-decoration: none; }
ul#filter li.current a, ul#filter a:hover { }
ul#filter li.current a { color: #ffffff; }
.filter-title h3 { margin-top:6px;}
ul#filter li.current { background:#000000; border: 1px solid #000000;}

/* Navigation  */
ul#filter-sidebar { width:260px; }
ul#filter-sidebar li {
	font-size:12px !important; 
	border-bottom: 1px  dashed #f4f4f4;
	font-size:10px;
	line-height: 12px;
	line-height:30px;
	padding-left:20px;
	background:url("/includes/images/read-more-arrow-dark.png") no-repeat 0px 10px;
}
ul#filter-sidebar li:hover, ul#filter-sidebar li.current { background:url("/includes/images/read-more-arrow-hover-dark.png") no-repeat 0px 10px; background-color:#f9f9f9; cursor:pointer; }
ul#filter-sidebar a { color: #777777; text-decoration: none; }
ul#filter-sidebar li.current a, ul#filter-sidebar a:hover { text-decoration: none; color:#333333;  }
ul#filter-sidebar li.current a { color: #333333;}



/*-------------------------------------------------------------------------------------------------*/
	/*SIDE BAR*/
/*-------------------------------------------------------------------------------------------------*/

.side-bar {
	width:260px;
	padding-left:40px;
}
.side-bar h5 { text-transform:uppercase; border-bottom:1px solid #f1f1f1; margin-bottom:10px; padding-bottom:5px;}

.side-bar4col {
	width:190px;
	padding-right:30px;
}
.side-bar4col h5 { text-transform:uppercase; border-bottom:1px solid #f1f1f1; margin-bottom:10px; padding-bottom:5px;}

.side-bar4col-right {
	width:190px;
	padding-left:30px;
}
.side-bar4col-right h5 { text-transform:uppercase; border-bottom:1px solid #f1f1f1; margin-bottom:10px; padding-bottom:5px;}

/* Navigation  */
ul.navigation-sidebar { width:260px; }
ul.navigation-sidebar li {
	font-size:12px !important; 
	border-bottom: 1px  dashed #f4f4f4;
	font-size:10px;
	line-height: 12px;
	line-height:30px;
	padding-left:20px;
	background:url("/includes/images/read-more-arrow-dark.png") no-repeat 0px 10px;
}
ul.navigation-sidebar li:hover, ul.navigation-sidebar li.current { background:url("/includes/images/read-more-arrow-hover-dark.png") no-repeat 0px 10px; background-color:#fff; cursor:pointer; }
ul.navigation-sidebar a { color: #777777; text-decoration: none; }
ul.navigation-sidebar li.current a, ul.navigation-sidebar a:hover { text-decoration: none; color:#000000;  }
ul.navigation-sidebar li.current a { color: #000000;}


/* Navigation 4col  */
ul.navigation-sidebar4col { width:190px; }
ul.navigation-sidebar4col li {
	font-size:12px !important; 
	border-bottom: 1px  dashed #f4f4f4;
	font-size:10px;
	line-height: 12px;
	line-height:30px;
	padding-left:20px;
	background:url("/includes/images/read-more-arrow-dark.png") no-repeat 0px 10px;
}
ul.navigation-sidebar4col li:hover, ul.navigation-sidebar4col li.current { background:url("/includes/images/read-more-arrow-hover-dark.png") no-repeat 0px 10px; background-color:#f9f9f9; cursor:pointer; }
ul.navigation-sidebar4col a { color: #777777; text-decoration: none; }
ul.navigation-sidebar4col li.current a, ul.navigation-sidebar4col a:hover { text-decoration: none; color:#333333;  }
ul.navigation-sidebar4col li.current a { color: #333333;}

/* Navigation 4col-right  */
ul.navigation-sidebar4col-right { width:190px; }
ul.navigation-sidebar4co-rightl li {
	font-size:12px !important; 
	border-bottom: 1px  dashed #f4f4f4;
	font-size:10px;
	line-height: 12px;
	line-height:30px;
	padding-left:20px;
	background:url("/includes/images/read-more-arrow-dark.png") no-repeat 0px 10px;
}
ul.navigation-sidebar4col-right li:hover, ul.navigation-sidebar4col-right li.current { background:url("/includes/images/read-more-arrow-hover-dark.png") no-repeat 0px 10px; background-color:#f9f9f9; cursor:pointer; }
ul.navigation-sidebar4col-right a { color: #777777; text-decoration: none; }
ul.navigation-sidebar4col-right li.current a, ul.navigation-sidebar4col-right a:hover { text-decoration: none; color:#333333;  }
ul.navigation-sidebar4col-right li.current a { color: #333333;}

/* Flicker  */
.side-bar .flickr { margin-top:0px; margin-right:18px;}
.side-bar4col .flickr { margin-top:0px; margin-right:18px;}
.side-bar4col-right .flickr { margin-top:0px; margin-right:18px;}
.box .flickr { margin-top:5px; margin-right:10px;}
.comment .flickr { margin-top:4px; margin-right:13px; margin-bottom:0px;}
.comment p { font-size:11px;}
.replay { font-size:10px;}

/*-------------------------------------------------------------------------------------------------*/
	/*SUPERFISH MENU */
/*-------------------------------------------------------------------------------------------------*/

/*** ESSENTIAL STYLES ***/
.sf-menu, .sf-menu * {
	margin: 0;
	padding: 0;
	list-style: none;
	font-family: arial;
	z-index:9499;
}
.sf-menu {
	line-height: 1.0;
}
.sf-menu ul {
	position: absolute;
	top: -999em;
	width: 10em; /* left offset of submenus need to match (see below) */
}
.sf-menu ul li {
	width: 158px;
}
.sf-menu li:hover {
	visibility:	inherit; /* fixes IE7 'sticky bug' */
}
.sf-menu li {
	float: left;
	position: relative;
}
.sf-menu a {
	display: block;
	position: relative;
}
.sf-menu li:hover ul,
.sf-menu li.sfHover ul {
	left: 0;
	top: 2.5em; /* match top ul list item height */
	z-index: 99;
}
ul.sf-menu li:hover li ul,
ul.sf-menu li.sfHover li ul {
	top: -999em;
}
ul.sf-menu li li:hover ul,
ul.sf-menu li li.sfHover ul {
	left: 10em; /* match ul width */
	top: 0;
}
ul.sf-menu li li:hover li ul,
ul.sf-menu li li.sfHover li ul {
	top: -999em;
}
ul.sf-menu li li li:hover ul,
ul.sf-menu li li li.sfHover ul {
	left: 10em; /* match ul width */
	top: 0;
}

/*** DEMO SKIN ***/
.sf-menu {
	float: right;
	margin-bottom: 1em;
	font-size:12px;
}
.sf-menu a {
	padding: 1em 1em;
	text-decoration:none;
	text-shadow:1px 1px #ffffff;
	
}
.sf-menu a, .sf-menu a:visited  { /* visited pseudo selector so IE6 applies text colour*/
	color: #444444;
}
.sf-menu li {
	background: #ffffff;
	top:6px;
	-moz-box-shadow:1px 1px 1px #aaa;
	-webkit-box-shadow:1px 1px 1px #aaa;
	box-shadow:1px 1px 1px #aaa;
}
.sf-menu li li {
	background: #ffffff;
	font-size:10px;
	border-bottom:1px solid #f2f2f2;
}
.sf-menu li li li {
	background: #ffffff;
	left:57px;
	border-bottom:1px solid #f2f2f2;
	top:0px;
}
.sf-menu li:hover, .sf-menu li.sfHover, .sf-menu a:focus, .sf-menu a:hover, .sf-menu a:active, .active a{
	background: #f1f1f1;
	outline: 0;
	color:#000000;
}

/*** arrows **/
.sf-menu a.sf-with-ul {
	padding-right: 30px;
	min-width: 1px; /* trigger IE7 hasLayout so spans position accurately */
}
.sf-sub-indicator {
	position: absolute;
	display: block;
	right: 15px;
	top: 40px; /* IE6 only */
	width: 10px;
	height: 10px;
	text-indent: -999em;
	overflow: hidden;
	background: url('/includes/images/arrows.png') no-repeat -10px -100px; /* 8-bit indexed alpha png. IE6 gets solid image only */
}
a > .sf-sub-indicator {  /* give all except IE6 the correct values */
	top: 12px;
	background-position: 0 -100px; /* use translucent arrow for modern browsers*/
}
/* apply hovers to modern browsers */
a:focus > .sf-sub-indicator,
a:hover > .sf-sub-indicator,
a:active > .sf-sub-indicator,
li:hover > a > .sf-sub-indicator,
li.sfHover > a > .sf-sub-indicator {
	background-position: -10px -100px; /* arrow hovers for modern browsers*/
}

/* point right for anchors in subs */
.sf-menu ul .sf-sub-indicator { background-position:  -10px 0; }
.sf-menu ul a > .sf-sub-indicator { background-position:  0 0; }
/* apply hovers to modern browsers */
.sf-menu ul a:focus > .sf-sub-indicator,
.sf-menu ul a:hover > .sf-sub-indicator,
.sf-menu ul a:active > .sf-sub-indicator,
.sf-menu ul li:hover > a > .sf-sub-indicator,
.sf-menu ul li.sfHover > a > .sf-sub-indicator {
	background-position: -10px 0; /* arrow hovers for modern browsers*/
}

/*-------------------------------------------------------------------------------------------------*/
	/*SLIDERS*/
/*-------------------------------------------------------------------------------------------------*/
.slider-area {
	width:900px !important;
	padding:20px;
	background:url('/includes/images/pattern/1.png');
	-moz-box-shadow:1px 1px 2px #aaa;
	-webkit-box-shadow:1px 1px 2px #aaa;
	box-shadow:1px 1px 2px #aaa;
}
.slider-area-inner {
	width:920px !important;
	padding:10px;
	margin-top:15px !important;
	background:url('/includes/images/pattern/1.png');
	-moz-box-shadow:1px 1px 2px #aaa;
	-webkit-box-shadow:1px 1px 2px #aaa;
	box-shadow:1px 1px 2px #aaa;
}
.slider-area-inner h1 { text-shadow:1px 1px #ffffff; text-transform:uppercase; margin-bottom:3px; margin-left:10px; line-height:40px; margin-right:8px;}
.slider-area-inner .descr { font-size:12px; text-transform:none; margin-top:12px; float:left; margin-bottom:0px;}
/*-------------------------------------------------------------------------------------------------*/
	/*MOSAIC SLIDER*/
/*-------------------------------------------------------------------------------------------------*/
.kwicks-box{
	width:940px;
}
.kwicks {
	/* recommended styles for kwicks ul container */
	list-style: none;
	position: relative;
	margin: 0;
	padding: 0;
	width:940px;
}
.kwicks li{
	/* these are required, but the values are up to you (must be pixel) */
	width: 225px;
	height: 350px;

	/*do not change these */
	display: block;
	overflow: hidden;
	padding: 0;  /* if you need padding, do so with an inner div (or implement your own box-model hack) */
}
.kwicks.horizontal li {
	/* This is optional and will be disregarded by the script.  However, it should be provided for non-JS enabled browsers. */
	/*margin-right: 5px; Set to same as spacing option. */	
	float: left;
	margin:0px;
}
.kwicks.horizontal #kwick_4 {
	margin-right: none; /* cancel margin on last kiwck (if you set a margin above) */
}
.kwicks.vertical #kwick_4 {
	margin-bottom: none; /* cancel margin on last kiwck (if you set a margin above) */
}
.accordian-slider-caption {
	bottom:0px;
	left:260px;
	position:absolute;
	color:#ffffff;
	padding:10px 20px;
	font-size:11px;
	background:#292929;
	width: 600px;
	text-shadow:none;
	text-decoration:none;
}
.accordian-slider-caption:hover{
		background:#000000;
}	

.accordian-slider-captiontitle {
	font-size:16px; 
	color:#fff; 
	display:block;
	line-height:26px;
	margin: 0 0 5px 0;
	text-decoration:none;
	text-transform:uppercase;
	font-family: Oswald;
}

/*****************************************/
/*General Mosaic Styles*/
.mosaic{padding:20px;background-color:#ffffff; width:900px;}
.details{ margin:5px 20px;}
.details-index{ 
	padding:20px;
	background:url('/includes/images/m2index1.png');
	height:150px;
	color:#ededed;
	text-shadow:0px 1px #393b3f;
}
.details-index h3{
	color:#ededed;
	text-shadow:0px 1px #393b3f;
	text-align:center;
}
.details-index h2{
	color:#ededed;
	text-shadow:0px 1px #393b3f;
	text-align:center;
}	
.details h4{color:#ededed; line-height:20px;}
.details p{ font:300 12px; color:#777777;}
.details a{ text-decoration:none !important; }


.mosaic-block {
	position:relative;
	overflow:hidden;
	text-decoration:none !important;
}
.mb1 {
	width:470px;
	height:200px;
	float:right;

}
.mb2 {
	width:195px;
	height:400px;
	float:left;
}
.mbindex {
	width:248px;
	height:190px;
}
.mb3 {
	width:235px;
	height:100px;
}
.mb4 {
	width:235px;
	height:300px;
	float:left;
}

.mb5 {
	width:470px;
	height:100px;
	float:left;
}

	.mosaic-backdrop {
		display:none;
		position:absolute;
		top:0;
		height:100%;
		width:100%;
		background:#111;
		text-decoration:none !important;
	}
	
	.mosaic-overlay {
		display:none;
		z-index:5;
		position:absolute;
		width:100%;
		height:100%;
		text-decoration:none !important;

	}
	
		/*** Custom Animation Styles (You can remove/add any styles below) ***/
		.circle .mosaic-overlay {
			background:url(/includes/images/hover-magnify.png) no-repeat center center;
			opacity:0;
			-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=00)";
			filter:alpha(opacity=00);
			display:none;
		}
		
		.fade .mosaic-overlay {
			opacity:0;
			-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=00)";
			filter:alpha(opacity=00);
			background:url(/includes/images/bg-black.png);
		}
		
		.bar .mosaic-overlay {
			bottom:-200px;
			height:200px;
			background:url(/includes/images/bg-black.png);
		}
		
		.bar2 .mosaic-overlay {
			bottom:-50px;
			height:100px;
			opacity:0.8;
			-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)";
			filter:alpha(opacity=80);
		}
		
		.bar2 .mosaic-overlay:hover {
			opacity:1;
			-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
			filter:alpha(opacity=100);
		}
		
		.bar3 .mosaic-overlay {
			top:-100px;
			height:100px;
			background:url(/includes/images/bg-black.png);
		}
		/*** End Animation Styles ***/

.static {
	color:#ffffff;
	text-shadow: 1px 1px #222222;
	background-image: url('/includes/images/gallery/stat-bg.jpg');
	background-repeat:repeat;
	padding-top:30px;
	padding-right:40px;
	padding-left:40px;
	height:330px;
}
.static div {
	float:left;
}
.static h3 {
	margin-top:10px;
	color:#ffffff;
}

/*-------------------------------------------------------------------------------------------------*/
	/*Features*/
/*-------------------------------------------------------------------------------------------------*/
.item a { 
	display:block;
	margin-bottom:12px;
	padding:5px;
	background:url('/includes/images/pattern/1.png');
	-moz-box-shadow:1px 1px 2px #aaa;
	-webkit-box-shadow:1px 1px 2px #aaa;
	box-shadow:1px 1px 2px #aaa;
}
.item {
	background:url('/includes/images/bg-fade.png') no-repeat center center;
	display: block;
}
/* button colours */
.bordered-form {margin-bottom:12px; padding:5px; background:url('/includes/images/pattern/1.png');}
.button_readmore {
    background:url("/includes/images/read-more-arrow-dark.png") no-repeat 5px 5px;
	background-color:#ffffff;
	border:1px solid #f1f1f1;
	color:#666666;
	padding-left:20px;
	padding-top:3px;
	padding-bottom:3px;
	padding-right:10px;
    font-size:10px;
    text-decoration:none;
	border-radius: 4px;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
}

a.button_readmore:hover {
	background:url("/includes/images/read-more-arrow-hover-dark.png") no-repeat 5px 5px;
	color:#ffffff;
	background-color:#000000;
	border:1px solid #000000;
	padding-left:20px;
	padding-top:3px;
	padding-bottom:3px;
	padding-right:10px;
	position:relative;
	text-decoration:none;
}

/*Sliding Text and Icon Menu Style*/
.sti-menu{
	width:940px;
	position:relative;
}
.sti-menu li{
	float:left;
	width:300px;
	height:100px;
	margin-right:20px;
	-moz-box-shadow:1px 1px 2px #aaa;
	-webkit-box-shadow:1px 1px 2px #aaa;
	box-shadow:1px 1px 2px #aaa;
}
.sti-menu li a{
	display:block;
	overflow:hidden;
	text-align:center;
	height:100%;
	width:100%;
	position:relative;
	background:#ffffff;
}
.sti-menu li a h2{
	text-transform:uppercase;
	color:#000000;
	position:absolute;
	left:100px;
	top:20px;
	font-size:24px;
}
.sti-menu li a h3{
	position:absolute;
	color:#777777;
	top:53px;
	left:100px;
	font-size:12px;
	font-family:Arial, Helvetica, sans-serif;
}
.sti-icon{
	top:15px;
	left:15px;
	width:70px;
	height:70px;
	position:absolute;
	background-position:top left;
	background-repeat:no-repeat;
	background-color:transparent;
}
.sti-icon-service{
	background-image:url(/includes/images/service.png);
}
.sti-icon-piggy{
	background-image:url(/includes/images/piggy.png);
}
.sti-icon-support{
	background-image:url(/includes/images/support.png);
}

/*-------------------------------------------------------------------------------------------------*/
	/*PRICING BOX*/
/*-------------------------------------------------------------------------------------------------*/
ul.list-box{margin:0; padding:0; list-style-type:none;}
ul.list-box > li{
	background:#e1e1e1;
	float:left;
}
ul.list-box  li:hover{
	position: relative;
	z-index: 100;
	top: -10px;
	cursor:pointer;
 }
.title-box {text-align:center; text-shadow:none; padding-bottom:15px; padding-top:15px;}
.box-header h3{
	margin-top:0px;
	}
.box-header h3{color:#FFF;}
.box-des{text-align:left;}
.pricing-box-container{background:#fafafa;text-align:left;	}
.list-box-content{ margin:0px 0px;padding:10px 25px 25px 25px; border:1px solid #ededed;}
.list-box-content ul{margin:0px auto;  padding:0; list-style-type:none;}
.list-box-content ul li{margin:0; padding:10px 0 10px 30px; list-style-type:none; background:url(/includes/images/check.png) no-repeat; background-position:center left; text-align:left}
.list-box-content ul li:hover{
	left:0px!important;
	top: 0px!important;}
.text-price{
	text-align:center;
	text-shadow:none;	
	padding:10px 0 10px 0;}
.text-price h3{color:#FFF;text-shadow:none; margin-top:0px;}
/*purple*/
.text-price.purple{
	background-color: #ff0099;
	}
.box-header.purple{
	border-bottom: 1px solid #ffffff;
	background-color: #CC0066;
	}
/*green*/
.text-price.green{
	background-color: #00CC33;
	}
.box-header.green{
	border-bottom: 1px solid #ffffff;
	background-color: #009900;
	}
/*blue*/
.text-price.blue{
	background-color: #0099FF;
	}
.box-header.blue{
	border-bottom: 1px solid #ffffff;
	background-color: #666666;
	}
.box-header.blue1{
	border-bottom: 1px solid #ffffff;
	background-color: #999999;
	}
/*dark*/
.box-header.dark{
	border-bottom: 1px solid #ffffff;
	background-color: #a9a9a9;
	}
.text-price.dark{
	background-color: #393b3f;
	}


/*-------------------------------------------------------------------------------------------------*/
	/*ICONS */
/*-------------------------------------------------------------------------------------------------*/
/* ---------------------normal */
.icon {
	background-color:#777777;
	width:16px;
	height:16px;
	margin-left:24px;
	margin-top:24px;
}

.icon:hover {
	background-color:#393b3f !important;
	cursor:pointer;
}
.icon-block .icon {
	margin-top:20px !important;
	margin-left:0px !important;
	margin-right:20px !important;	
}


/* /normal */

/* ---------------------big */
.big-round-icon {
	width:64px;
	height:64px;
	background: #292929;
	margin-right:20px;
	-webkit-border-radius: 64px;
	-moz-border-radius: 64px;
	border-radius: 64px;
	-webkit-transition: background-color 0.1s linear, color 0.1s linear;
	-moz-transition: background-color 0.1s linear, color 0.1s linear;
	border-color:#000;
}
.icon-black-big {
	background-color:#ffffff;
	width:16px;
	height:16px;
	margin-left:24px;
	margin-top:24px;
}

.big-round-icon-black {
	width:64px;
	height:64px;
	background: #242424;
	margin-right:20px;
	margin-bottom:10px;
	-webkit-border-radius: 64px;
	-moz-border-radius: 64px;
	border-radius: 64px;
	-webkit-transition: background-color 0.1s linear, color 0.1s linear;
	-moz-transition: background-color 0.1s linear, color 0.1s linear;
	border-color:#000;
}

.big-round-icon-gray {
	width:64px;
	height:64px;
	background: #e1e1e1;
	margin-right:20px;
	margin-bottom:10px;
	-webkit-border-radius: 64px;
	-moz-border-radius: 64px;
	border-radius: 64px;
	-webkit-transition: background-color 0.1s linear, color 0.1s linear;
	-moz-transition: background-color 0.1s linear, color 0.1s linear;
	border-color:#000;
}

.big-rounded-icon-white {
	padding-left:16px;
	padding-top:16px;
	width:32px;
	height:32px;
	background: #ffffff;
	margin-top:0px;
	margin-right:20px;
	margin-bottom:10px;
	background:url('/includes/images/rounded-bg.png');
}
.service .big-rounded-icon-white{ margin-top:2px;}
.serv .icon-white-big{ margin-top:3px;}
.serv h5 { margin-left:15px;}
.icon-white-big {
	background-color:#000000;
	width:16px;
	height:16px;
}
.footer .icon-white-big { margin-right:10px; margin-top:2px;}
.icon-gray-big {
	background-color:#666666;
	width:16px;
	height:16px;
	margin-left:24px;
	margin-top:24px;
}
/* /big */

/* ---------------------medium */
/* /medium */

/* ---------------------small */
.small-round-icon-white {
	width:32px;
	height:32px;
	background:url('/includes/images/icon-bg.png');
	margin-right:10px;
	
}
.faq .small-round-icon-white {
	margin-right:10px;
	margin-bottom:10px;
}
.faq h5 { margin-top:4px;}
.icon-white-small {
	background-color:#666666;
	width:16px;
	height:16px;
	margin-left:8px;
	margin-top:8px;
}
.footer .icon-white-small{ margin-left:0px; margin-right:13px; float:left;}
.small-round-icon-gray{
	width:32px;
	height:32px;
	background: #e1e1e1;
	margin-right:10px;
	-webkit-border-radius: 32px;
	-moz-border-radius: 32px;
	border-radius: 32px;
	-webkit-transition: background-color 0.1s linear, color 0.1s linear;
	-moz-transition: background-color 0.1s linear, color 0.1s linear;
	border-color:#000;
}

.icon-gray-small {
	background-color:#666666;
	width:16px;
	height:16px;
	margin-left:8px;
	margin-top:8px;
}
.icon-gray-small:hover {
	background-color:#393b3f !important;
}
.icon-white-small:hover {
	background-color:#393b3f !important;
}
/* ---------------------black */
.small-round-icon-black {
	width:32px;
	height:32px;
	background: #292929;
	margin-right:10px;
	-webkit-border-radius: 32px;
	-moz-border-radius: 32px;
	border-radius: 32px;
	-webkit-transition: background-color 0.1s linear, color 0.1s linear;
	-moz-transition: background-color 0.1s linear, color 0.1s linear;
	border-color:#000;
}
.icon-black-small {
	background-color:#ffffff;
	width:16px;
	height:16px;
	margin-left:8px !important;
	margin-top:8px !important;
}

.icon-black-small:hover {
	background-color:#ffffff !important;
}


.icon1 {background-image:url('/includes/images/icons.png'); background-position: 0px 0px;}
.icon2 {background-image:url('/includes/images/icons.png'); background-position: -16px 0px;}
.icon3 {background-image:url('/includes/images/icons.png'); background-position: -32px 0px;}
.icon4 {background-image:url('/includes/images/icons.png'); background-position: -48px 0px;}
.icon5 {background-image:url('/includes/images/icons.png'); background-position: -64px 0px;}
.icon6 {background-image:url('/includes/images/icons.png'); background-position: -80px 0px;}
.icon7 {background-image:url('/includes/images/icons.png'); background-position: -96px 0px;}
.icon8 {background-image:url('/includes/images/icons.png'); background-position: -112px 0px;}
.icon9 {background-image:url('/includes/images/icons.png'); background-position: -128px 0px;}
.icon10 {background-image:url('/includes/images/icons.png'); background-position: -144px 0px;}
.icon11 {background-image:url('/includes/images/icons.png'); background-position: -160px 0px;}
.icon12 {background-image:url('/includes/images/icons.png'); background-position: -176px 0px;}
.icon13 {background-image:url('/includes/images/icons.png'); background-position: -192px 0px;}
.icon14 {background-image:url('/includes/images/icons.png'); background-position: -208px 0px;}
.icon15 {background-image:url('/includes/images/icons.png'); background-position: -224px 0px;}
.icon16 {background-image:url('/includes/images/icons.png'); background-position: -240px 0px;}
.icon17 {background-image:url('/includes/images/icons.png'); background-position: -256px 0px;}
.icon18 {background-image:url('/includes/images/icons.png'); background-position: -272px 0px;}
.icon19 {background-image:url('/includes/images/icons.png'); background-position: -288px 0px;}
.icon20 {background-image:url('/includes/images/icons.png'); background-position: -304px 0px;}

.icon21 {background-image:url('/includes/images/icons.png'); background-position: 0px -16px;}
.icon22 {background-image:url('/includes/images/icons.png'); background-position: -16px -16px;}
.icon23 {background-image:url('/includes/images/icons.png'); background-position: -32px -16px;}
.icon24 {background-image:url('/includes/images/icons.png'); background-position: -48px -16px;}
.icon25 {background-image:url('/includes/images/icons.png'); background-position: -64px -16px;}
.icon26 {background-image:url('/includes/images/icons.png'); background-position: -80px -16px;}
.icon27 {background-image:url('/includes/images/icons.png'); background-position: -96px -16px;}
.icon28 {background-image:url('/includes/images/icons.png'); background-position: -112px -16px;}
.icon29 {background-image:url('/includes/images/icons.png'); background-position: -128px -16px;}
.icon30 {background-image:url('/includes/images/icons.png'); background-position: -144px -16px;}
.icon31 {background-image:url('/includes/images/icons.png'); background-position: -160px -16px;}
.icon32 {background-image:url('/includes/images/icons.png'); background-position: -176px -16px;}
.icon33 {background-image:url('/includes/images/icons.png'); background-position: -192px -16px;}
.icon34 {background-image:url('/includes/images/icons.png'); background-position: -208px -16px;}
.icon35 {background-image:url('/includes/images/icons.png'); background-position: -224px -16px;}
.icon36 {background-image:url('/includes/images/icons.png'); background-position: -240px -16px;}
.icon37 {background-image:url('/includes/images/icons.png'); background-position: -256px -16px;}
.icon38 {background-image:url('/includes/images/icons.png'); background-position: -272px -16px;}
.icon39 {background-image:url('/includes/images/icons.png'); background-position: -288px -16px;}
.icon40 {background-image:url('/includes/images/icons.png'); background-position: -304px -16px;}

.icon41 {background-image:url('/includes/images/icons.png'); background-position: 0px -32px;}
.icon42 {background-image:url('/includes/images/icons.png'); background-position: -16px -32px;}
.icon43 {background-image:url('/includes/images/icons.png'); background-position: -32px -32px;}
.icon44 {background-image:url('/includes/images/icons.png'); background-position: -48px -32px;}
.icon45 {background-image:url('/includes/images/icons.png'); background-position: -64px -32px;}
.icon46 {background-image:url('/includes/images/icons.png'); background-position: -80px -32px;}
.icon47 {background-image:url('/includes/images/icons.png'); background-position: -96px -32px;}
.icon48 {background-image:url('/includes/images/icons.png'); background-position: -112px -32px;}
.icon49 {background-image:url('/includes/images/icons.png'); background-position: -128px -32px;}
.icon50 {background-image:url('/includes/images/icons.png'); background-position: -144px -32px;}
.icon51 {background-image:url('/includes/images/icons.png'); background-position: -160px -32px;}
.icon52 {background-image:url('/includes/images/icons.png'); background-position: -176px -32px;}
.icon53 {background-image:url('/includes/images/icons.png'); background-position: -192px -32px;}
.icon54 {background-image:url('/includes/images/icons.png'); background-position: -208px -32px;}
.icon55 {background-image:url('/includes/images/icons.png'); background-position: -224px -32px;}
.icon56 {background-image:url('/includes/images/icons.png'); background-position: -240px -32px;}
.icon57 {background-image:url('/includes/images/icons.png'); background-position: -256px -32px;}
.icon58 {background-image:url('/includes/images/icons.png'); background-position: -272px -32px;}
.icon59 {background-image:url('/includes/images/icons.png'); background-position: -288px -32px;}
.icon60 {background-image:url('/includes/images/icons.png'); background-position: -304px -32px;}

.icon61 {background-image:url('/includes/images/icons.png'); background-position: 0px -48px;}
.icon62 {background-image:url('/includes/images/icons.png'); background-position: -16px -48px;}
.icon63 {background-image:url('/includes/images/icons.png'); background-position: -32px -48px;}
.icon64 {background-image:url('/includes/images/icons.png'); background-position: -48px -48px;}
.icon65 {background-image:url('/includes/images/icons.png'); background-position: -64px -48px;}
.icon66 {background-image:url('/includes/images/icons.png'); background-position: -80px -48px;}
.icon67 {background-image:url('/includes/images/icons.png'); background-position: -96px -48px;}
.icon68 {background-image:url('/includes/images/icons.png'); background-position: -112px -48px;}
.icon69 {background-image:url('/includes/images/icons.png'); background-position: -128px -48px;}
.icon70 {background-image:url('/includes/images/icons.png'); background-position: -144px -48px;}
.icon71 {background-image:url('/includes/images/icons.png'); background-position: -160px -48px;}
.icon72 {background-image:url('/includes/images/icons.png'); background-position: -176px -48px;}
.icon73 {background-image:url('/includes/images/icons.png'); background-position: -192px -48px;}
.icon74 {background-image:url('/includes/images/icons.png'); background-position: -208px -48px;}
.icon75 {background-image:url('/includes/images/icons.png'); background-position: -224px -48px;}
.icon76 {background-image:url('/includes/images/icons.png'); background-position: -240px -48px;}
.icon77 {background-image:url('/includes/images/icons.png'); background-position: -256px -48px;}
.icon78 {background-image:url('/includes/images/icons.png'); background-position: -272px -48px;}
.icon79 {background-image:url('/includes/images/icons.png'); background-position: -288px -48px;}
.icon80 {background-image:url('/includes/images/icons.png'); background-position: -304px -48px;}

.icon81 {background-image:url('/includes/images/icons.png'); background-position: 0px -64px;}
.icon82 {background-image:url('/includes/images/icons.png'); background-position: -16px -64px;}
.icon83 {background-image:url('/includes/images/icons.png'); background-position: -32px -64px;}
.icon84 {background-image:url('/includes/images/icons.png'); background-position: -48px -64px;}
.icon85 {background-image:url('/includes/images/icons.png'); background-position: -64px -64px;}
.icon86 {background-image:url('/includes/images/icons.png'); background-position: -80px -64px;}
.icon87 {background-image:url('/includes/images/icons.png'); background-position: -96px -64px;}
.icon88 {background-image:url('/includes/images/icons.png'); background-position: -112px -64px;}
.icon89 {background-image:url('/includes/images/icons.png'); background-position: -128px -64px;}
.icon90 {background-image:url('/includes/images/icons.png'); background-position: -144px -64px;}
.icon91 {background-image:url('/includes/images/icons.png'); background-position: -160px -64px;}
.icon92 {background-image:url('/includes/images/icons.png'); background-position: -176px -64px;}
.icon93 {background-image:url('/includes/images/icons.png'); background-position: -192px -64px;}
.icon94 {background-image:url('/includes/images/icons.png'); background-position: -208px -64px;}
.icon95 {background-image:url('/includes/images/icons.png'); background-position: -224px -64px;}
.icon96 {background-image:url('/includes/images/icons.png'); background-position: -240px -64px;}
.icon97 {background-image:url('/includes/images/icons.png'); background-position: -256px -64px;}
.icon98 {background-image:url('/includes/images/icons.png'); background-position: -272px -64px;}
.icon99 {background-image:url('/includes/images/icons.png'); background-position: -288px -64px;}
.icon100 {background-image:url('/includes/images/icons.png'); background-position: -304px -64px;}

.icon101 {background-image:url('/includes/images/icons.png'); background-position: 0px -80px;}
.icon102 {background-image:url('/includes/images/icons.png'); background-position: -16px -80px;}
.icon103 {background-image:url('/includes/images/icons.png'); background-position: -32px -80px;}
.icon104 {background-image:url('/includes/images/icons.png'); background-position: -48px -80px;}
.icon105 {background-image:url('/includes/images/icons.png'); background-position: -64px -80px;}
.icon106 {background-image:url('/includes/images/icons.png'); background-position: -80px -80px;}
.icon107 {background-image:url('/includes/images/icons.png'); background-position: -96px -80px;}
.icon108 {background-image:url('/includes/images/icons.png'); background-position: -112px -80px;}
.icon109 {background-image:url('/includes/images/icons.png'); background-position: -128px -80px;}
.icon110 {background-image:url('/includes/images/icons.png'); background-position: -144px -80px;}
.icon111 {background-image:url('/includes/images/icons.png'); background-position: -160px -80px;}
.icon112 {background-image:url('/includes/images/icons.png'); background-position: -176px -80px;}
.icon113 {background-image:url('/includes/images/icons.png'); background-position: -192px -80px;}
.icon114 {background-image:url('/includes/images/icons.png'); background-position: -208px -80px;}
.icon115 {background-image:url('/includes/images/icons.png'); background-position: -224px -80px;}
.icon116 {background-image:url('/includes/images/icons.png'); background-position: -240px -80px;}
.icon117 {background-image:url('/includes/images/icons.png'); background-position: -256px -80px;}
.icon118 {background-image:url('/includes/images/icons.png'); background-position: -272px -80px;}
.icon119 {background-image:url('/includes/images/icons.png'); background-position: -288px -80px;}
.icon120 {background-image:url('/includes/images/icons.png'); background-position: -304px -80px;}

.icon121 {background-image:url('/includes/images/icons.png'); background-position: 0px -96px;}
.icon122 {background-image:url('/includes/images/icons.png'); background-position: -16px -96px;}
.icon123 {background-image:url('/includes/images/icons.png'); background-position: -32px -96px;}
.icon124 {background-image:url('/includes/images/icons.png'); background-position: -48px -96px;}
.icon125 {background-image:url('/includes/images/icons.png'); background-position: -64px -96px;}
.icon126 {background-image:url('/includes/images/icons.png'); background-position: -80px -96px;}
.icon127 {background-image:url('/includes/images/icons.png'); background-position: -96px -96px;}
.icon128 {background-image:url('/includes/images/icons.png'); background-position: -112px -96px;}
.icon129 {background-image:url('/includes/images/icons.png'); background-position: -128px -96px;}
.icon130 {background-image:url('/includes/images/icons.png'); background-position: -144px -96px;}
.icon131 {background-image:url('/includes/images/icons.png'); background-position: -160px -96px;}
.icon132 {background-image:url('/includes/images/icons.png'); background-position: -176px -96px;}
.icon133 {background-image:url('/includes/images/icons.png'); background-position: -192px -96px;}
.icon134 {background-image:url('/includes/images/icons.png'); background-position: -208px -96px;}
.icon135 {background-image:url('/includes/images/icons.png'); background-position: -224px -96px;}
.icon136 {background-image:url('/includes/images/icons.png'); background-position: -240px -96px;}
.icon137 {background-image:url('/includes/images/icons.png'); background-position: -256px -96px;}
.icon138 {background-image:url('/includes/images/icons.png'); background-position: -272px -96px;}
.icon139 {background-image:url('/includes/images/icons.png'); background-position: -288px -96px;}
.icon140 {background-image:url('/includes/images/icons.png'); background-position: -304px -96px;}

.icon141 {background-image:url('/includes/images/icons.png'); background-position: 0px -112px;}
.icon142 {background-image:url('/includes/images/icons.png'); background-position: -16px -112px;}
.icon143 {background-image:url('/includes/images/icons.png'); background-position: -32px -112px;}
.icon144 {background-image:url('/includes/images/icons.png'); background-position: -48px -112px;}
.icon145 {background-image:url('/includes/images/icons.png'); background-position: -64px -112px;}
.icon146 {background-image:url('/includes/images/icons.png'); background-position: -80px -112px;}
.icon147 {background-image:url('/includes/images/icons.png'); background-position: -96px -112px;}
.icon148 {background-image:url('/includes/images/icons.png'); background-position: -112px -112px;}
.icon149 {background-image:url('/includes/images/icons.png'); background-position: -128px -112px;}
.icon150 {background-image:url('/includes/images/icons.png'); background-position: -144px -112px;}
.icon151 {background-image:url('/includes/images/icons.png'); background-position: -160px -112px;}
.icon152 {background-image:url('/includes/images/icons.png'); background-position: -176px -112px;}
.icon153 {background-image:url('/includes/images/icons.png'); background-position: -192px -112px;}
.icon154 {background-image:url('/includes/images/icons.png'); background-position: -208px -112px;}
.icon155 {background-image:url('/includes/images/icons.png'); background-position: -224px -112px;}
.icon156 {background-image:url('/includes/images/icons.png'); background-position: -240px -112px;}
.icon157 {background-image:url('/includes/images/icons.png'); background-position: -256px -112px;}
.icon158 {background-image:url('/includes/images/icons.png'); background-position: -272px -112px;}
.icon159 {background-image:url('/includes/images/icons.png'); background-position: -288px -112px;}
.icon160 {background-image:url('/includes/images/icons.png'); background-position: -304px -112px;}

.icon161 {background-image:url('/includes/images/icons.png'); background-position: 0px -128px;}
.icon162 {background-image:url('/includes/images/icons.png'); background-position: -16px -128px;}
.icon163 {background-image:url('/includes/images/icons.png'); background-position: -32px -128px;}
.icon164 {background-image:url('/includes/images/icons.png'); background-position: -48px -128px;}
.icon165 {background-image:url('/includes/images/icons.png'); background-position: -64px -128px;}
.icon166 {background-image:url('/includes/images/icons.png'); background-position: -80px -128px;}
.icon167 {background-image:url('/includes/images/icons.png'); background-position: -96px -128px;}
.icon168 {background-image:url('/includes/images/icons.png'); background-position: -112px -128px;}
.icon169 {background-image:url('/includes/images/icons.png'); background-position: -128px -128px;}
.icon170 {background-image:url('/includes/images/icons.png'); background-position: -144px -128px;}
.icon171 {background-image:url('/includes/images/icons.png'); background-position: -160px -128px;}
.icon172 {background-image:url('/includes/images/icons.png'); background-position: -176px -128px;}
.icon173 {background-image:url('/includes/images/icons.png'); background-position: -192px -128px;}
.icon174 {background-image:url('/includes/images/icons.png'); background-position: -208px -128px;}
.icon175 {background-image:url('/includes/images/icons.png'); background-position: -224px -128px;}
.icon176 {background-image:url('/includes/images/icons.png'); background-position: -240px -128px;}
.icon177 {background-image:url('/includes/images/icons.png'); background-position: -256px -128px;}
.icon178 {background-image:url('/includes/images/icons.png'); background-position: -272px -128px;}
.icon179 {background-image:url('/includes/images/icons.png'); background-position: -288px -128px;}
.icon180 {background-image:url('/includes/images/icons.png'); background-position: -304px -128px;}

.icon181 {background-image:url('/includes/images/icons.png'); background-position: 0px -144px;}
.icon182 {background-image:url('/includes/images/icons.png'); background-position: -16px -144px;}
.icon183 {background-image:url('/includes/images/icons.png'); background-position: -32px -144px;}
.icon184 {background-image:url('/includes/images/icons.png'); background-position: -48px -144px;}
.icon185 {background-image:url('/includes/images/icons.png'); background-position: -64px -144px;}
.icon186 {background-image:url('/includes/images/icons.png'); background-position: -80px -144px;}
.icon187 {background-image:url('/includes/images/icons.png'); background-position: -96px -144px;}
.icon188 {background-image:url('/includes/images/icons.png'); background-position: -112px -144px;}
.icon189 {background-image:url('/includes/images/icons.png'); background-position: -128px -144px;}
.icon190 {background-image:url('/includes/images/icons.png'); background-position: -144px -144px;}
.icon191 {background-image:url('/includes/images/icons.png'); background-position: -160px -144px;}
.icon192 {background-image:url('/includes/images/icons.png'); background-position: -176px -144px;}
.icon193 {background-image:url('/includes/images/icons.png'); background-position: -192px -144px;}
.icon194 {background-image:url('/includes/images/icons.png'); background-position: -208px -144px;}
.icon195 {background-image:url('/includes/images/icons.png'); background-position: -224px -144px;}
.icon196 {background-image:url('/includes/images/icons.png'); background-position: -240px -144px;}
.icon197 {background-image:url('/includes/images/icons.png'); background-position: -256px -144px;}
.icon198 {background-image:url('/includes/images/icons.png'); background-position: -272px -144px;}
.icon199 {background-image:url('/includes/images/icons.png'); background-position: -288px -144px;}
.icon200 {background-image:url('/includes/images/icons.png'); background-position: -304px -144px;}

.icon201 {background-image:url('/includes/images/icons.png'); background-position: 0px -160px;}
.icon202 {background-image:url('/includes/images/icons.png'); background-position: -16px -160px;}
.icon203 {background-image:url('/includes/images/icons.png'); background-position: -32px -160px;}
.icon204 {background-image:url('/includes/images/icons.png'); background-position: -48px -160px;}
.icon205 {background-image:url('/includes/images/icons.png'); background-position: -64px -160px;}
.icon206 {background-image:url('/includes/images/icons.png'); background-position: -80px -160px;}
.icon207 {background-image:url('/includes/images/icons.png'); background-position: -96px -160px;}
.icon208 {background-image:url('/includes/images/icons.png'); background-position: -112px -160px;}
.icon209 {background-image:url('/includes/images/icons.png'); background-position: -128px -160px;}
.icon210 {background-image:url('/includes/images/icons.png'); background-position: -144px -160px;}
.icon211 {background-image:url('/includes/images/icons.png'); background-position: -160px -160px;}
.icon212 {background-image:url('/includes/images/icons.png'); background-position: -176px -160px;}
.icon213 {background-image:url('/includes/images/icons.png'); background-position: -192px -160px;}
.icon214 {background-image:url('/includes/images/icons.png'); background-position: -208px -160px;}
.icon215 {background-image:url('/includes/images/icons.png'); background-position: -224px -160px;}
.icon216 {background-image:url('/includes/images/icons.png'); background-position: -240px -160px;}
.icon217 {background-image:url('/includes/images/icons.png'); background-position: -256px -160px;}
.icon218 {background-image:url('/includes/images/icons.png'); background-position: -272px -160px;}
.icon219 {background-image:url('/includes/images/icons.png'); background-position: -288px -160px;}
.icon220 {background-image:url('/includes/images/icons.png'); background-position: -304px -160px;}

.icon221 {background-image:url('/includes/images/icons.png'); background-position: 0px -176px;}
.icon222 {background-image:url('/includes/images/icons.png'); background-position: -16px -176px;}
.icon223 {background-image:url('/includes/images/icons.png'); background-position: -32px -176px;}
.icon224 {background-image:url('/includes/images/icons.png'); background-position: -48px -176px;}
.icon225 {background-image:url('/includes/images/icons.png'); background-position: -64px -176px;}
.icon226 {background-image:url('/includes/images/icons.png'); background-position: -80px -176px;}
.icon227 {background-image:url('/includes/images/icons.png'); background-position: -96px -176px;}
.icon228 {background-image:url('/includes/images/icons.png'); background-position: -112px -176px;}
.icon229 {background-image:url('/includes/images/icons.png'); background-position: -128px -176px;}
.icon230 {background-image:url('/includes/images/icons.png'); background-position: -144px -176px;}
.icon231 {background-image:url('/includes/images/icons.png'); background-position: -160px -176px;}
.icon232 {background-image:url('/includes/images/icons.png'); background-position: -176px -176px;}
.icon233 {background-image:url('/includes/images/icons.png'); background-position: -192px -176px;}
.icon234 {background-image:url('/includes/images/icons.png'); background-position: -208px -176px;}
.icon235 {background-image:url('/includes/images/icons.png'); background-position: -224px -176px;}
.icon236 {background-image:url('/includes/images/icons.png'); background-position: -240px -176px;}
.icon237 {background-image:url('/includes/images/icons.png'); background-position: -256px -176px;}
.icon238 {background-image:url('/includes/images/icons.png'); background-position: -272px -176px;}
.icon239 {background-image:url('/includes/images/icons.png'); background-position: -288px -176px;}
.icon240 {background-image:url('/includes/images/icons.png'); background-position: -304px -176px;}

.icon241 {background-image:url('/includes/images/icons.png'); background-position: -0px -192px;}
.icon242 {background-image:url('/includes/images/icons.png'); background-position: -16px -192px;}
.icon243 {background-image:url('/includes/images/icons.png'); background-position: -32px -192px;}

.icon1-gray {background-image:url('/includes/images/icons-gray.png'); background-position: 0px 0px;}
.icon2-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px 0px;}
.icon3-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px 0px;}
.icon4-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -48px 0px;}
.icon5-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -64px 0px;}
.icon6-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -80px 0px;}
.icon7-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -96px 0px;}
.icon8-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -112px 0px;}
.icon9-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -128px 0px;}
.icon10-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -144px 0px;}
.icon11-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -160px 0px;}
.icon12-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -176px 0px;}
.icon13-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -192px 0px;}
.icon14-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -208px 0px;}
.icon15-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -224px 0px;}
.icon16-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -240px 0px;}
.icon17-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -256px 0px;}
.icon18-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -272px 0px;}
.icon19-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -288px 0px;}
.icon20-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -304px 0px;}

.icon21-gray {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -16px;}
.icon22-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -16px;}
.icon23-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -16px;}
.icon24-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -48px -16px;}
.icon25-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -64px -16px;}
.icon26-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -80px -16px;}
.icon27-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -96px -16px;}
.icon28-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -112px -16px;}
.icon29-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -128px -16px;}
.icon30-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -144px -16px;}
.icon31-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -160px -16px;}
.icon32-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -176px -16px;}
.icon33-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -192px -16px;}
.icon34-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -208px -16px;}
.icon35-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -224px -16px;}
.icon36-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -240px -16px;}
.icon37-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -256px -16px;}
.icon38-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -272px -16px;}
.icon39-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -288px -16px;}
.icon40-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -304px -16px;}

.icon41-gray {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -32px;}
.icon42-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -32px;}
.icon43-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -32px;}
.icon44-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -48px -32px;}
.icon45-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -64px -32px;}
.icon46-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -80px -32px;}
.icon47-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -96px -32px;}
.icon48-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -112px -32px;}
.icon49-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -128px -32px;}
.icon50-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -144px -32px;}
.icon51-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -160px -32px;}
.icon52-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -176px -32px;}
.icon53-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -192px -32px;}
.icon54-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -208px -32px;}
.icon55-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -224px -32px;}
.icon56-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -240px -32px;}
.icon57-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -256px -32px;}
.icon58-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -272px -32px;}
.icon59-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -288px -32px;}
.icon60-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -304px -32px;}

.icon61-gray {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -48px;}
.icon62-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -48px;}
.icon63-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -48px;}
.icon64-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -48px -48px;}
.icon65-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -64px -48px;}
.icon66-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -80px -48px;}
.icon67-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -96px -48px;}
.icon68-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -112px -48px;}
.icon69-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -128px -48px;}
.icon70-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -144px -48px;}
.icon71-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -160px -48px;}
.icon72-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -176px -48px;}
.icon73-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -192px -48px;}
.icon74-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -208px -48px;}
.icon75-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -224px -48px;}
.icon76-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -240px -48px;}
.icon77-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -256px -48px;}
.icon78-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -272px -48px;}
.icon79-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -288px -48px;}
.icon80-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -304px -48px;}

.icon81-gray {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -64px;}
.icon82-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -64px;}
.icon83-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -64px;}
.icon84-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -48px -64px;}
.icon85-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -64px -64px;}
.icon86-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -80px -64px;}
.icon87-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -96px -64px;}
.icon88-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -112px -64px;}
.icon89-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -128px -64px;}
.icon90-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -144px -64px;}
.icon91-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -160px -64px;}
.icon92-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -176px -64px;}
.icon93-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -192px -64px;}
.icon94-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -208px -64px;}
.icon95-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -224px -64px;}
.icon96-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -240px -64px;}
.icon97-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -256px -64px;}
.icon98-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -272px -64px;}
.icon99-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -288px -64px;}
.icon100-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -304px -64px;}

.icon101-gray {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -80px;}
.icon102-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -80px;}
.icon103-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -80px;}
.icon104-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -48px -80px;}
.icon105-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -64px -80px;}
.icon106-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -80px -80px;}
.icon107-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -96px -80px;}
.icon108-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -112px -80px;}
.icon109-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -128px -80px;}
.icon110-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -144px -80px;}
.icon111-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -160px -80px;}
.icon112-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -176px -80px;}
.icon113-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -192px -80px;}
.icon114-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -208px -80px;}
.icon115-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -224px -80px;}
.icon116-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -240px -80px;}
.icon117-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -256px -80px;}
.icon118-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -272px -80px;}
.icon119-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -288px -80px;}
.icon120-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -304px -80px;}

.icon121-gray {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -96px;}
.icon122-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -96px;}
.icon123-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -96px;}
.icon124-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -48px -96px;}
.icon125-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -64px -96px;}
.icon126-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -80px -96px;}
.icon127-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -96px -96px;}
.icon128-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -112px -96px;}
.icon129-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -128px -96px;}
.icon130-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -144px -96px;}
.icon131-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -160px -96px;}
.icon132-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -176px -96px;}
.icon133-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -192px -96px;}
.icon134-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -208px -96px;}
.icon135-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -224px -96px;}
.icon136-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -240px -96px;}
.icon137-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -256px -96px;}
.icon138-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -272px -96px;}
.icon139-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -288px -96px;}
.icon140-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -304px -96px;}

.icon141-gray {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -112px;}
.icon142-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -112px;}
.icon143-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -112px;}
.icon144-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -48px -112px;}
.icon145-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -64px -112px;}
.icon146-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -80px -112px;}
.icon147-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -96px -112px;}
.icon148-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -112px -112px;}
.icon149-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -128px -112px;}
.icon150-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -144px -112px;}
.icon151-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -160px -112px;}
.icon152-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -176px -112px;}
.icon153-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -192px -112px;}
.icon154-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -208px -112px;}
.icon155-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -224px -112px;}
.icon156-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -240px -112px;}
.icon157-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -256px -112px;}
.icon158-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -272px -112px;}
.icon159-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -288px -112px;}
.icon160-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -304px -112px;}

.icon161-gray {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -128px;}
.icon162-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -128px;}
.icon163-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -128px;}
.icon164-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -48px -128px;}
.icon165-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -64px -128px;}
.icon166-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -80px -128px;}
.icon167-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -96px -128px;}
.icon168-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -112px -128px;}
.icon169-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -128px -128px;}
.icon170-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -144px -128px;}
.icon171-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -160px -128px;}
.icon172-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -176px -128px;}
.icon173-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -192px -128px;}
.icon174-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -208px -128px;}
.icon175-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -224px -128px;}
.icon176-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -240px -128px;}
.icon177-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -256px -128px;}
.icon178-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -272px -128px;}
.icon179-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -288px -128px;}
.icon180-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -304px -128px;}

.icon181-gray {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -144px;}
.icon182-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -144px;}
.icon183-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -144px;}
.icon184-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -48px -144px;}
.icon185-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -64px -144px;}
.icon186-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -80px -144px;}
.icon187-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -96px -144px;}
.icon188-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -112px -144px;}
.icon189-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -128px -144px;}
.icon190-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -144px -144px;}
.icon191-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -160px -144px;}
.icon192-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -176px -144px;}
.icon193-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -192px -144px;}
.icon194-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -208px -144px;}
.icon195-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -224px -144px;}
.icon196-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -240px -144px;}
.icon197-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -256px -144px;}
.icon198-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -272px -144px;}
.icon199-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -288px -144px;}
.icon200-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -304px -144px;}

.icon201-gray {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -160px;}
.icon202-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -160px;}
.icon203-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -160px;}
.icon204-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -48px -160px;}
.icon205-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -64px -160px;}
.icon206-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -80px -160px;}
.icon207-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -96px -160px;}
.icon208-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -112px -160px;}
.icon209-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -128px -160px;}
.icon210-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -144px -160px;}
.icon211-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -160px -160px;}
.icon212-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -176px -160px;}
.icon213-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -192px -160px;}
.icon214-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -208px -160px;}
.icon215-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -224px -160px;}
.icon216-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -240px -160px;}
.icon217-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -256px -160px;}
.icon218-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -272px -160px;}
.icon219-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -288px -160px;}
.icon220-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -304px -160px;}

.icon221-gray {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -176px;}
.icon222-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -176px;}
.icon223-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -176px;}
.icon224-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -48px -176px;}
.icon225-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -64px -176px;}
.icon226-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -80px -176px;}
.icon227-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -96px -176px;}
.icon228-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -112px -176px;}
.icon229-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -128px -176px;}
.icon230-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -144px -176px;}
.icon231-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -160px -176px;}
.icon232-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -176px -176px;}
.icon233-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -192px -176px;}
.icon234-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -208px -176px;}
.icon235-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -224px -176px;}
.icon236-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -240px -176px;}
.icon237-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -256px -176px;}
.icon238-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -272px -176px;}
.icon239-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -288px -176px;}
.icon240-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -304px -176px;}

.icon241-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -0px -192px;}
.icon242-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -192px;}
.icon243-gray {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -192px;}

.icon1-white {background-image:url('/includes/images/icons-white.png'); background-position: 0px 0px;}
.icon2-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px 0px;}
.icon3-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px 0px;}
.icon4-white {background-image:url('/includes/images/icons-white.png'); background-position: -48px 0px;}
.icon5-white {background-image:url('/includes/images/icons-white.png'); background-position: -64px 0px;}
.icon6-white {background-image:url('/includes/images/icons-white.png'); background-position: -80px 0px;}
.icon7-white {background-image:url('/includes/images/icons-white.png'); background-position: -96px 0px;}
.icon8-white {background-image:url('/includes/images/icons-white.png'); background-position: -112px 0px;}
.icon9-white {background-image:url('/includes/images/icons-white.png'); background-position: -128px 0px;}
.icon10-white {background-image:url('/includes/images/icons-white.png'); background-position: -144px 0px;}
.icon11-white {background-image:url('/includes/images/icons-white.png'); background-position: -160px 0px;}
.icon12-white {background-image:url('/includes/images/icons-white.png'); background-position: -176px 0px;}
.icon13-white {background-image:url('/includes/images/icons-white.png'); background-position: -192px 0px;}
.icon14-white {background-image:url('/includes/images/icons-white.png'); background-position: -208px 0px;}
.icon15-white {background-image:url('/includes/images/icons-white.png'); background-position: -224px 0px;}
.icon16-white {background-image:url('/includes/images/icons-white.png'); background-position: -240px 0px;}
.icon17-white {background-image:url('/includes/images/icons-white.png'); background-position: -256px 0px;}
.icon18-white {background-image:url('/includes/images/icons-white.png'); background-position: -272px 0px;}
.icon19-white {background-image:url('/includes/images/icons-white.png'); background-position: -288px 0px;}
.icon20-white {background-image:url('/includes/images/icons-white.png'); background-position: -304px 0px;}

.icon21-white {background-image:url('/includes/images/icons-white.png'); background-position: 0px -16px;}
.icon22-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px -16px;}
.icon23-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px -16px;}
.icon24-white {background-image:url('/includes/images/icons-white.png'); background-position: -48px -16px;}
.icon25-white {background-image:url('/includes/images/icons-white.png'); background-position: -64px -16px;}
.icon26-white {background-image:url('/includes/images/icons-white.png'); background-position: -80px -16px;}
.icon27-white {background-image:url('/includes/images/icons-white.png'); background-position: -96px -16px;}
.icon28-white {background-image:url('/includes/images/icons-white.png'); background-position: -112px -16px;}
.icon29-white {background-image:url('/includes/images/icons-white.png'); background-position: -128px -16px;}
.icon30-white {background-image:url('/includes/images/icons-white.png'); background-position: -144px -16px;}
.icon31-white {background-image:url('/includes/images/icons-white.png'); background-position: -160px -16px;}
.icon32-white {background-image:url('/includes/images/icons-white.png'); background-position: -176px -16px;}
.icon33-white {background-image:url('/includes/images/icons-white.png'); background-position: -192px -16px;}
.icon34-white {background-image:url('/includes/images/icons-white.png'); background-position: -208px -16px;}
.icon35-white {background-image:url('/includes/images/icons-white.png'); background-position: -224px -16px;}
.icon36-white {background-image:url('/includes/images/icons-white.png'); background-position: -240px -16px;}
.icon37-white {background-image:url('/includes/images/icons-white.png'); background-position: -256px -16px;}
.icon38-white {background-image:url('/includes/images/icons-white.png'); background-position: -272px -16px;}
.icon39-white {background-image:url('/includes/images/icons-white.png'); background-position: -288px -16px;}
.icon40-white {background-image:url('/includes/images/icons-white.png'); background-position: -304px -16px;}

.icon41-white {background-image:url('/includes/images/icons-white.png'); background-position: 0px -32px;}
.icon42-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px -32px;}
.icon43-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px -32px;}
.icon44-white {background-image:url('/includes/images/icons-white.png'); background-position: -48px -32px;}
.icon45-white {background-image:url('/includes/images/icons-white.png'); background-position: -64px -32px;}
.icon46-white {background-image:url('/includes/images/icons-white.png'); background-position: -80px -32px;}
.icon47-white {background-image:url('/includes/images/icons-white.png'); background-position: -96px -32px;}
.footer .icon47-white {background-image:url('/includes/images/icons-gray.png'); background-position: -96px -32px;}
.icon48-white {background-image:url('/includes/images/icons-white.png'); background-position: -112px -32px;}
.icon49-white {background-image:url('/includes/images/icons-white.png'); background-position: -128px -32px;}
.icon50-white {background-image:url('/includes/images/icons-white.png'); background-position: -144px -32px;}
.icon51-white {background-image:url('/includes/images/icons-white.png'); background-position: -160px -32px;}
.icon52-white {background-image:url('/includes/images/icons-white.png'); background-position: -176px -32px;}
.icon53-white {background-image:url('/includes/images/icons-white.png'); background-position: -192px -32px;}
.icon54-white {background-image:url('/includes/images/icons-white.png'); background-position: -208px -32px;}
.icon55-white {background-image:url('/includes/images/icons-white.png'); background-position: -224px -32px;}
.icon56-white {background-image:url('/includes/images/icons-white.png'); background-position: -240px -32px;}
.icon57-white {background-image:url('/includes/images/icons-white.png'); background-position: -256px -32px;}
.icon58-white {background-image:url('/includes/images/icons-white.png'); background-position: -272px -32px;}
.icon59-white {background-image:url('/includes/images/icons-white.png'); background-position: -288px -32px;}
.icon60-white {background-image:url('/includes/images/icons-white.png'); background-position: -304px -32px;}

.icon61-white {background-image:url('/includes/images/icons-white.png'); background-position: 0px -48px;}
.icon62-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px -48px;}
.icon63-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px -48px;}
.icon64-white {background-image:url('/includes/images/icons-white.png'); background-position: -48px -48px;}
.blog .icon64-white {background-image:url('/includes/images/icons-gray.png'); background-position: -48px -48px;}
.icon65-white {background-image:url('/includes/images/icons-white.png'); background-position: -64px -48px;}
.icon66-white {background-image:url('/includes/images/icons-white.png'); background-position: -80px -48px;}
.icon67-white {background-image:url('/includes/images/icons-white.png'); background-position: -96px -48px;}
.icon68-white {background-image:url('/includes/images/icons-white.png'); background-position: -112px -48px;}
.icon69-white {background-image:url('/includes/images/icons-white.png'); background-position: -128px -48px;}
.icon70-white {background-image:url('/includes/images/icons-white.png'); background-position: -144px -48px;}
.icon71-white {background-image:url('/includes/images/icons-white.png'); background-position: -160px -48px;}
.icon72-white {background-image:url('/includes/images/icons-white.png'); background-position: -176px -48px;}
.icon73-white {background-image:url('/includes/images/icons-white.png'); background-position: -192px -48px;}
.icon74-white {background-image:url('/includes/images/icons-white.png'); background-position: -208px -48px;}
.icon75-white {background-image:url('/includes/images/icons-white.png'); background-position: -224px -48px;}
.icon76-white {background-image:url('/includes/images/icons-white.png'); background-position: -240px -48px;}
.icon77-white {background-image:url('/includes/images/icons-white.png'); background-position: -256px -48px;}
.icon78-white {background-image:url('/includes/images/icons-white.png'); background-position: -272px -48px;}
.icon79-white {background-image:url('/includes/images/icons-white.png'); background-position: -288px -48px;}
.icon80-white {background-image:url('/includes/images/icons-white.png'); background-position: -304px -48px;}

.icon81-white {background-image:url('/includes/images/icons-white.png'); background-position: 0px -64px;}
.blog .icon81-white {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -64px;}
.icon82-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px -64px;}
.icon83-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px -64px;}
.icon84-white {background-image:url('/includes/images/icons-white.png'); background-position: -48px -64px;}
.icon85-white {background-image:url('/includes/images/icons-white.png'); background-position: -64px -64px;}
.icon86-white {background-image:url('/includes/images/icons-white.png'); background-position: -80px -64px;}
.icon87-white {background-image:url('/includes/images/icons-white.png'); background-position: -96px -64px;}
.icon88-white {background-image:url('/includes/images/icons-white.png'); background-position: -112px -64px;}
.icon89-white {background-image:url('/includes/images/icons-white.png'); background-position: -128px -64px;}
.icon90-white {background-image:url('/includes/images/icons-white.png'); background-position: -144px -64px;}
.icon91-white {background-image:url('/includes/images/icons-white.png'); background-position: -160px -64px;}
.icon92-white {background-image:url('/includes/images/icons-white.png'); background-position: -176px -64px;}
.icon93-white {background-image:url('/includes/images/icons-white.png'); background-position: -192px -64px;}
.icon94-white {background-image:url('/includes/images/icons-white.png'); background-position: -208px -64px;}
.icon95-white {background-image:url('/includes/images/icons-white.png'); background-position: -224px -64px;}
.icon96-white {background-image:url('/includes/images/icons-white.png'); background-position: -240px -64px;}
.icon97-white {background-image:url('/includes/images/icons-white.png'); background-position: -256px -64px;}
.icon98-white {background-image:url('/includes/images/icons-white.png'); background-position: -272px -64px;}
.icon99-white {background-image:url('/includes/images/icons-white.png'); background-position: -288px -64px;}
.icon100-white {background-image:url('/includes/images/icons-white.png'); background-position: -304px -64px;}

.icon101-white {background-image:url('/includes/images/icons-white.png'); background-position: 0px -80px;}
.footer .icon101-white {background-image:url('/includes/images/icons-gray.png'); background-position: 0px -80px;}
.icon102-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px -80px;}
.icon103-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px -80px;}
.icon104-white {background-image:url('/includes/images/icons-white.png'); background-position: -48px -80px;}
.icon105-white {background-image:url('/includes/images/icons-white.png'); background-position: -64px -80px;}
.icon106-white {background-image:url('/includes/images/icons-white.png'); background-position: -80px -80px;}
.icon107-white {background-image:url('/includes/images/icons-white.png'); background-position: -96px -80px;}
.icon108-white {background-image:url('/includes/images/icons-white.png'); background-position: -112px -80px;}
.icon109-white {background-image:url('/includes/images/icons-white.png'); background-position: -128px -80px;}
.icon110-white {background-image:url('/includes/images/icons-white.png'); background-position: -144px -80px;}
.icon111-white {background-image:url('/includes/images/icons-white.png'); background-position: -160px -80px;}
.icon112-white {background-image:url('/includes/images/icons-white.png'); background-position: -176px -80px;}
.icon113-white {background-image:url('/includes/images/icons-white.png'); background-position: -192px -80px;}
.icon114-white {background-image:url('/includes/images/icons-white.png'); background-position: -208px -80px;}
.icon115-white {background-image:url('/includes/images/icons-white.png'); background-position: -224px -80px;}
.icon116-white {background-image:url('/includes/images/icons-white.png'); background-position: -240px -80px;}
.icon117-white {background-image:url('/includes/images/icons-white.png'); background-position: -256px -80px;}
.icon118-white {background-image:url('/includes/images/icons-white.png'); background-position: -272px -80px;}
.icon119-white {background-image:url('/includes/images/icons-white.png'); background-position: -288px -80px;}
.icon120-white {background-image:url('/includes/images/icons-white.png'); background-position: -304px -80px;}

.icon121-white {background-image:url('/includes/images/icons-white.png'); background-position: 0px -96px;}
.icon122-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px -96px;}
.icon123-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px -96px;}
.blog .icon123-white {background-image:url('/includes/images/icons-gray.png'); background-position: -32px -96px;}
.icon124-white {background-image:url('/includes/images/icons-white.png'); background-position: -48px -96px;}
.icon125-white {background-image:url('/includes/images/icons-white.png'); background-position: -64px -96px;}
.icon126-white {background-image:url('/includes/images/icons-white.png'); background-position: -80px -96px;}
.icon127-white {background-image:url('/includes/images/icons-white.png'); background-position: -96px -96px;}
.icon128-white {background-image:url('/includes/images/icons-white.png'); background-position: -112px -96px;}
.icon129-white {background-image:url('/includes/images/icons-white.png'); background-position: -128px -96px;}
.icon130-white {background-image:url('/includes/images/icons-white.png'); background-position: -144px -96px;}
.icon131-white {background-image:url('/includes/images/icons-white.png'); background-position: -160px -96px;}
.icon132-white {background-image:url('/includes/images/icons-white.png'); background-position: -176px -96px;}
.icon133-white {background-image:url('/includes/images/icons-white.png'); background-position: -192px -96px;}
.icon134-white {background-image:url('/includes/images/icons-white.png'); background-position: -208px -96px;}
.icon135-white {background-image:url('/includes/images/icons-white.png'); background-position: -224px -96px;}
.icon136-white {background-image:url('/includes/images/icons-white.png'); background-position: -240px -96px;}
.icon137-white {background-image:url('/includes/images/icons-white.png'); background-position: -256px -96px;}
.icon138-white {background-image:url('/includes/images/icons-white.png'); background-position: -272px -96px;}
.icon139-white {background-image:url('/includes/images/icons-white.png'); background-position: -288px -96px;}
.icon140-white {background-image:url('/includes/images/icons-white.png'); background-position: -304px -96px;}

.icon141-white {background-image:url('/includes/images/icons-white.png'); background-position: 0px -112px;}
.icon142-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px -112px;}
.icon143-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px -112px;}
.icon144-white {background-image:url('/includes/images/icons-white.png'); background-position: -48px -112px;}
.icon145-white {background-image:url('/includes/images/icons-white.png'); background-position: -64px -112px;}
.icon146-white {background-image:url('/includes/images/icons-white.png'); background-position: -80px -112px;}
.icon147-white {background-image:url('/includes/images/icons-white.png'); background-position: -96px -112px;}
.icon148-white {background-image:url('/includes/images/icons-white.png'); background-position: -112px -112px;}
.icon149-white {background-image:url('/includes/images/icons-white.png'); background-position: -128px -112px;}
.icon150-white {background-image:url('/includes/images/icons-white.png'); background-position: -144px -112px;}
.icon151-white {background-image:url('/includes/images/icons-white.png'); background-position: -160px -112px;}
.icon152-white {background-image:url('/includes/images/icons-white.png'); background-position: -176px -112px;}
.icon153-white {background-image:url('/includes/images/icons-white.png'); background-position: -192px -112px;}
.icon154-white {background-image:url('/includes/images/icons-white.png'); background-position: -208px -112px;}
.icon155-white {background-image:url('/includes/images/icons-white.png'); background-position: -224px -112px;}
.icon156-white {background-image:url('/includes/images/icons-white.png'); background-position: -240px -112px;}
.icon157-white {background-image:url('/includes/images/icons-white.png'); background-position: -256px -112px;}
.icon158-white {background-image:url('/includes/images/icons-white.png'); background-position: -272px -112px;}
.icon159-white {background-image:url('/includes/images/icons-white.png'); background-position: -288px -112px;}
.icon160-white {background-image:url('/includes/images/icons-white.png'); background-position: -304px -112px;}

.icon161-white {background-image:url('/includes/images/icons-white.png'); background-position: 0px -128px;}
.icon162-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px -128px;}
.icon163-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px -128px;}
.icon164-white {background-image:url('/includes/images/icons-white.png'); background-position: -48px -128px;}
.icon165-white {background-image:url('/includes/images/icons-white.png'); background-position: -64px -128px;}
.icon166-white {background-image:url('/includes/images/icons-white.png'); background-position: -80px -128px;}
.icon167-white {background-image:url('/includes/images/icons-white.png'); background-position: -96px -128px;}
.icon168-white {background-image:url('/includes/images/icons-white.png'); background-position: -112px -128px;}
.icon169-white {background-image:url('/includes/images/icons-white.png'); background-position: -128px -128px;}
.icon170-white {background-image:url('/includes/images/icons-white.png'); background-position: -144px -128px;}
.span-24 .icon170-white {background-image:url('/includes/images/icons-gray.png'); background-position: -144px -128px;}
.icon171-white {background-image:url('/includes/images/icons-white.png'); background-position: -160px -128px;}
.icon172-white {background-image:url('/includes/images/icons-white.png'); background-position: -176px -128px;}
.icon173-white {background-image:url('/includes/images/icons-white.png'); background-position: -192px -128px;}
.icon174-white {background-image:url('/includes/images/icons-white.png'); background-position: -208px -128px;}
.icon175-white {background-image:url('/includes/images/icons-white.png'); background-position: -224px -128px;}
.icon176-white {background-image:url('/includes/images/icons-white.png'); background-position: -240px -128px;}
.icon177-white {background-image:url('/includes/images/icons-white.png'); background-position: -256px -128px;}
.icon178-white {background-image:url('/includes/images/icons-white.png'); background-position: -272px -128px;}
.icon179-white {background-image:url('/includes/images/icons-white.png'); background-position: -288px -128px;}
.icon180-white {background-image:url('/includes/images/icons-white.png'); background-position: -304px -128px;}

.icon181-white {background-image:url('/includes/images/icons-white.png'); background-position: 0px -144px;}
.icon182-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px -144px;}
.blog .icon182-white {background-image:url('/includes/images/icons-gray.png'); background-position: -16px -144px;}
.icon183-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px -144px;}
.icon184-white {background-image:url('/includes/images/icons-white.png'); background-position: -48px -144px;}
.icon185-white {background-image:url('/includes/images/icons-white.png'); background-position: -64px -144px;}
.icon186-white {background-image:url('/includes/images/icons-white.png'); background-position: -80px -144px;}
.icon187-white {background-image:url('/includes/images/icons-white.png'); background-position: -96px -144px;}
.icon188-white {background-image:url('/includes/images/icons-white.png'); background-position: -112px -144px;}
.icon189-white {background-image:url('/includes/images/icons-white.png'); background-position: -128px -144px;}
.icon190-white {background-image:url('/includes/images/icons-white.png'); background-position: -144px -144px;}
.icon191-white {background-image:url('/includes/images/icons-white.png'); background-position: -160px -144px;}
.icon192-white {background-image:url('/includes/images/icons-white.png'); background-position: -176px -144px;}
.icon193-white {background-image:url('/includes/images/icons-white.png'); background-position: -192px -144px;}
.footer .icon193-white {background-image:url('/includes/images/icons-gray.png'); background-position: -192px -144px;}
.icon194-white {background-image:url('/includes/images/icons-white.png'); background-position: -208px -144px;}
.icon195-white {background-image:url('/includes/images/icons-white.png'); background-position: -224px -144px;}
.icon196-white {background-image:url('/includes/images/icons-white.png'); background-position: -240px -144px;}
.icon197-white {background-image:url('/includes/images/icons-white.png'); background-position: -256px -144px;}
.icon198-white {background-image:url('/includes/images/icons-white.png'); background-position: -272px -144px;}
.icon199-white {background-image:url('/includes/images/icons-white.png'); background-position: -288px -144px;}
.icon200-white {background-image:url('/includes/images/icons-white.png'); background-position: -304px -144px;}

.icon201-white {background-image:url('/includes/images/icons-white.png'); background-position: 0px -160px;}
.icon202-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px -160px;}
.icon203-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px -160px;}
.icon204-white {background-image:url('/includes/images/icons-white.png'); background-position: -48px -160px;}
.icon205-white {background-image:url('/includes/images/icons-white.png'); background-position: -64px -160px;}
.icon206-white {background-image:url('/includes/images/icons-white.png'); background-position: -80px -160px;}
.icon207-white {background-image:url('/includes/images/icons-white.png'); background-position: -96px -160px;}
.icon208-white {background-image:url('/includes/images/icons-white.png'); background-position: -112px -160px;}
.icon209-white {background-image:url('/includes/images/icons-white.png'); background-position: -128px -160px;}
.icon210-white {background-image:url('/includes/images/icons-white.png'); background-position: -144px -160px;}
.icon211-white {background-image:url('/includes/images/icons-white.png'); background-position: -160px -160px;}
.icon212-white {background-image:url('/includes/images/icons-white.png'); background-position: -176px -160px;}
.icon213-white {background-image:url('/includes/images/icons-white.png'); background-position: -192px -160px;}
.icon214-white {background-image:url('/includes/images/icons-white.png'); background-position: -208px -160px;}
.icon215-white {background-image:url('/includes/images/icons-white.png'); background-position: -224px -160px;}
.icon216-white {background-image:url('/includes/images/icons-white.png'); background-position: -240px -160px;}
.icon217-white {background-image:url('/includes/images/icons-white.png'); background-position: -256px -160px;}
.icon218-white {background-image:url('/includes/images/icons-white.png'); background-position: -272px -160px;}
.icon219-white {background-image:url('/includes/images/icons-white.png'); background-position: -288px -160px;}
.icon220-white {background-image:url('/includes/images/icons-white.png'); background-position: -304px -160px;}

.icon221-white {background-image:url('/includes/images/icons-white.png'); background-position: 0px -176px;}
.icon222-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px -176px;}
.icon223-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px -176px;}
.icon224-white {background-image:url('/includes/images/icons-white.png'); background-position: -48px -176px;}
.icon225-white {background-image:url('/includes/images/icons-white.png'); background-position: -64px -176px;}
.icon226-white {background-image:url('/includes/images/icons-white.png'); background-position: -80px -176px;}
.icon227-white {background-image:url('/includes/images/icons-white.png'); background-position: -96px -176px;}
.icon228-white {background-image:url('/includes/images/icons-white.png'); background-position: -112px -176px;}
.icon229-white {background-image:url('/includes/images/icons-white.png'); background-position: -128px -176px;}
.icon230-white {background-image:url('/includes/images/icons-white.png'); background-position: -144px -176px;}
.icon231-white {background-image:url('/includes/images/icons-white.png'); background-position: -160px -176px;}
.icon232-white {background-image:url('/includes/images/icons-white.png'); background-position: -176px -176px;}
.icon233-white {background-image:url('/includes/images/icons-white.png'); background-position: -192px -176px;}
.icon234-white {background-image:url('/includes/images/icons-white.png'); background-position: -208px -176px;}
.icon235-white {background-image:url('/includes/images/icons-white.png'); background-position: -224px -176px;}
.icon236-white {background-image:url('/includes/images/icons-white.png'); background-position: -240px -176px;}
.icon237-white {background-image:url('/includes/images/icons-white.png'); background-position: -256px -176px;}
.icon238-white {background-image:url('/includes/images/icons-white.png'); background-position: -272px -176px;}
.icon239-white {background-image:url('/includes/images/icons-white.png'); background-position: -288px -176px;}
.icon240-white {background-image:url('/includes/images/icons-white.png'); background-position: -304px -176px;}

.icon241-white {background-image:url('/includes/images/icons-white.png'); background-position: -0px -192px;}
.icon242-white {background-image:url('/includes/images/icons-white.png'); background-position: -16px -192px;}
.icon243-white {background-image:url('/includes/images/icons-white.png'); background-position: -32px -192px;}



.icon1-black {background-image:url('/includes/images/icons-black.png'); background-position: 0px 0px;}
.icon2-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px 0px;}
.icon3-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px 0px;}
.icon4-black {background-image:url('/includes/images/icons-black.png'); background-position: -48px 0px;}
.icon5-black {background-image:url('/includes/images/icons-black.png'); background-position: -64px 0px;}
.icon6-black {background-image:url('/includes/images/icons-black.png'); background-position: -80px 0px;}
.icon7-black {background-image:url('/includes/images/icons-black.png'); background-position: -96px 0px;}
.icon8-black {background-image:url('/includes/images/icons-black.png'); background-position: -112px 0px;}
.icon9-black {background-image:url('/includes/images/icons-black.png'); background-position: -128px 0px;}
.icon10-black {background-image:url('/includes/images/icons-black.png'); background-position: -144px 0px;}
.icon11-black {background-image:url('/includes/images/icons-black.png'); background-position: -160px 0px;}
.icon12-black {background-image:url('/includes/images/icons-black.png'); background-position: -176px 0px;}
.icon13-black {background-image:url('/includes/images/icons-black.png'); background-position: -192px 0px;}
.icon14-black {background-image:url('/includes/images/icons-black.png'); background-position: -208px 0px;}
.icon15-black {background-image:url('/includes/images/icons-black.png'); background-position: -224px 0px;}
.icon16-black {background-image:url('/includes/images/icons-black.png'); background-position: -240px 0px;}
.icon17-black {background-image:url('/includes/images/icons-black.png'); background-position: -256px 0px;}
.icon18-black {background-image:url('/includes/images/icons-black.png'); background-position: -272px 0px;}
.icon19-black {background-image:url('/includes/images/icons-black.png'); background-position: -288px 0px;}
.icon20-black {background-image:url('/includes/images/icons-black.png'); background-position: -304px 0px;}

.icon21-black {background-image:url('/includes/images/icons-black.png'); background-position: 0px -16px;}
.icon22-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px -16px;}
.icon23-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px -16px;}
.icon24-black {background-image:url('/includes/images/icons-black.png'); background-position: -48px -16px;}
.icon25-black {background-image:url('/includes/images/icons-black.png'); background-position: -64px -16px;}
.icon26-black {background-image:url('/includes/images/icons-black.png'); background-position: -80px -16px;}
.icon27-black {background-image:url('/includes/images/icons-black.png'); background-position: -96px -16px;}
.icon28-black {background-image:url('/includes/images/icons-black.png'); background-position: -112px -16px;}
.icon29-black {background-image:url('/includes/images/icons-black.png'); background-position: -128px -16px;}
.icon30-black {background-image:url('/includes/images/icons-black.png'); background-position: -144px -16px;}
.icon31-black {background-image:url('/includes/images/icons-black.png'); background-position: -160px -16px;}
.icon32-black {background-image:url('/includes/images/icons-black.png'); background-position: -176px -16px;}
.icon33-black {background-image:url('/includes/images/icons-black.png'); background-position: -192px -16px;}
.icon34-black {background-image:url('/includes/images/icons-black.png'); background-position: -208px -16px;}
.icon35-black {background-image:url('/includes/images/icons-black.png'); background-position: -224px -16px;}
.icon36-black {background-image:url('/includes/images/icons-black.png'); background-position: -240px -16px;}
.icon37-black {background-image:url('/includes/images/icons-black.png'); background-position: -256px -16px;}
.icon38-black {background-image:url('/includes/images/icons-black.png'); background-position: -272px -16px;}
.icon39-black {background-image:url('/includes/images/icons-black.png'); background-position: -288px -16px;}
.icon40-black {background-image:url('/includes/images/icons-black.png'); background-position: -304px -16px;}

.icon41-black {background-image:url('/includes/images/icons-black.png'); background-position: 0px -32px;}
.icon42-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px -32px;}
.icon43-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px -32px;}
.icon44-black {background-image:url('/includes/images/icons-black.png'); background-position: -48px -32px;}
.icon45-black {background-image:url('/includes/images/icons-black.png'); background-position: -64px -32px;}
.icon46-black {background-image:url('/includes/images/icons-black.png'); background-position: -80px -32px;}
.icon47-black {background-image:url('/includes/images/icons-black.png'); background-position: -96px -32px;}
.icon48-black {background-image:url('/includes/images/icons-black.png'); background-position: -112px -32px;}
.icon49-black {background-image:url('/includes/images/icons-black.png'); background-position: -128px -32px;}
.icon50-black {background-image:url('/includes/images/icons-black.png'); background-position: -144px -32px;}
.icon51-black {background-image:url('/includes/images/icons-black.png'); background-position: -160px -32px;}
.icon52-black {background-image:url('/includes/images/icons-black.png'); background-position: -176px -32px;}
.icon53-black {background-image:url('/includes/images/icons-black.png'); background-position: -192px -32px;}
.icon54-black {background-image:url('/includes/images/icons-black.png'); background-position: -208px -32px;}
.icon55-black {background-image:url('/includes/images/icons-black.png'); background-position: -224px -32px;}
.icon56-black {background-image:url('/includes/images/icons-black.png'); background-position: -240px -32px;}
.icon57-black {background-image:url('/includes/images/icons-black.png'); background-position: -256px -32px;}
.icon58-black {background-image:url('/includes/images/icons-black.png'); background-position: -272px -32px;}
.icon59-black {background-image:url('/includes/images/icons-black.png'); background-position: -288px -32px;}
.icon60-black {background-image:url('/includes/images/icons-black.png'); background-position: -304px -32px;}

.icon61-black {background-image:url('/includes/images/icons-black.png'); background-position: 0px -48px;}
.icon62-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px -48px;}
.icon63-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px -48px;}
.icon64-black {background-image:url('/includes/images/icons-black.png'); background-position: -48px -48px;}
.icon65-black {background-image:url('/includes/images/icons-black.png'); background-position: -64px -48px;}
.icon66-black {background-image:url('/includes/images/icons-black.png'); background-position: -80px -48px;}
.icon67-black {background-image:url('/includes/images/icons-black.png'); background-position: -96px -48px;}
.icon68-black {background-image:url('/includes/images/icons-black.png'); background-position: -112px -48px;}
.icon69-black {background-image:url('/includes/images/icons-black.png'); background-position: -128px -48px;}
.icon70-black {background-image:url('/includes/images/icons-black.png'); background-position: -144px -48px;}
.icon71-black {background-image:url('/includes/images/icons-black.png'); background-position: -160px -48px;}
.icon72-black {background-image:url('/includes/images/icons-black.png'); background-position: -176px -48px;}
.icon73-black {background-image:url('/includes/images/icons-black.png'); background-position: -192px -48px;}
.icon74-black {background-image:url('/includes/images/icons-black.png'); background-position: -208px -48px;}
.icon75-black {background-image:url('/includes/images/icons-black.png'); background-position: -224px -48px;}
.icon76-black {background-image:url('/includes/images/icons-black.png'); background-position: -240px -48px;}
.icon77-black {background-image:url('/includes/images/icons-black.png'); background-position: -256px -48px;}
.icon78-black {background-image:url('/includes/images/icons-black.png'); background-position: -272px -48px;}
.icon79-black {background-image:url('/includes/images/icons-black.png'); background-position: -288px -48px;}
.icon80-black {background-image:url('/includes/images/icons-black.png'); background-position: -304px -48px;}

.icon81-black {background-image:url('/includes/images/icons-black.png'); background-position: 0px -64px;}
.icon82-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px -64px;}
.icon83-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px -64px;}
.icon84-black {background-image:url('/includes/images/icons-black.png'); background-position: -48px -64px;}
.icon85-black {background-image:url('/includes/images/icons-black.png'); background-position: -64px -64px;}
.icon86-black {background-image:url('/includes/images/icons-black.png'); background-position: -80px -64px;}
.icon87-black {background-image:url('/includes/images/icons-black.png'); background-position: -96px -64px;}
.icon88-black {background-image:url('/includes/images/icons-black.png'); background-position: -112px -64px;}
.icon89-black {background-image:url('/includes/images/icons-black.png'); background-position: -128px -64px;}
.icon90-black {background-image:url('/includes/images/icons-black.png'); background-position: -144px -64px;}
.icon91-black {background-image:url('/includes/images/icons-black.png'); background-position: -160px -64px;}
.icon92-black {background-image:url('/includes/images/icons-black.png'); background-position: -176px -64px;}
.icon93-black {background-image:url('/includes/images/icons-black.png'); background-position: -192px -64px;}
.icon94-black {background-image:url('/includes/images/icons-black.png'); background-position: -208px -64px;}
.icon95-black {background-image:url('/includes/images/icons-black.png'); background-position: -224px -64px;}
.icon96-black {background-image:url('/includes/images/icons-black.png'); background-position: -240px -64px;}
.icon97-black {background-image:url('/includes/images/icons-black.png'); background-position: -256px -64px;}
.icon98-black {background-image:url('/includes/images/icons-black.png'); background-position: -272px -64px;}
.icon99-black {background-image:url('/includes/images/icons-black.png'); background-position: -288px -64px;}
.icon100-black {background-image:url('/includes/images/icons-black.png'); background-position: -304px -64px;}

.icon101-black {background-image:url('/includes/images/icons-black.png'); background-position: 0px -80px;}
.icon102-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px -80px;}
.icon103-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px -80px;}
.icon104-black {background-image:url('/includes/images/icons-black.png'); background-position: -48px -80px;}
.icon105-black {background-image:url('/includes/images/icons-black.png'); background-position: -64px -80px;}
.icon106-black {background-image:url('/includes/images/icons-black.png'); background-position: -80px -80px;}
.icon107-black {background-image:url('/includes/images/icons-black.png'); background-position: -96px -80px;}
.icon108-black {background-image:url('/includes/images/icons-black.png'); background-position: -112px -80px;}
.icon109-black {background-image:url('/includes/images/icons-black.png'); background-position: -128px -80px;}
.icon110-black {background-image:url('/includes/images/icons-black.png'); background-position: -144px -80px;}
.icon111-black {background-image:url('/includes/images/icons-black.png'); background-position: -160px -80px;}
.icon112-black {background-image:url('/includes/images/icons-black.png'); background-position: -176px -80px;}
.icon113-black {background-image:url('/includes/images/icons-black.png'); background-position: -192px -80px;}
.icon114-black {background-image:url('/includes/images/icons-black.png'); background-position: -208px -80px;}
.icon115-black {background-image:url('/includes/images/icons-black.png'); background-position: -224px -80px;}
.icon116-black {background-image:url('/includes/images/icons-black.png'); background-position: -240px -80px;}
.icon117-black {background-image:url('/includes/images/icons-black.png'); background-position: -256px -80px;}
.icon118-black {background-image:url('/includes/images/icons-black.png'); background-position: -272px -80px;}
.icon119-black {background-image:url('/includes/images/icons-black.png'); background-position: -288px -80px;}
.icon120-black {background-image:url('/includes/images/icons-black.png'); background-position: -304px -80px;}

.icon121-black {background-image:url('/includes/images/icons-black.png'); background-position: 0px -96px;}
.icon122-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px -96px;}
.icon123-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px -96px;}
.icon124-black {background-image:url('/includes/images/icons-black.png'); background-position: -48px -96px;}
.icon125-black {background-image:url('/includes/images/icons-black.png'); background-position: -64px -96px;}
.icon126-black {background-image:url('/includes/images/icons-black.png'); background-position: -80px -96px;}
.icon127-black {background-image:url('/includes/images/icons-black.png'); background-position: -96px -96px;}
.icon128-black {background-image:url('/includes/images/icons-black.png'); background-position: -112px -96px;}
.icon129-black {background-image:url('/includes/images/icons-black.png'); background-position: -128px -96px;}
.icon130-black {background-image:url('/includes/images/icons-black.png'); background-position: -144px -96px;}
.icon131-black {background-image:url('/includes/images/icons-black.png'); background-position: -160px -96px;}
.icon132-black {background-image:url('/includes/images/icons-black.png'); background-position: -176px -96px;}
.icon133-black {background-image:url('/includes/images/icons-black.png'); background-position: -192px -96px;}
.icon134-black {background-image:url('/includes/images/icons-black.png'); background-position: -208px -96px;}
.icon135-black {background-image:url('/includes/images/icons-black.png'); background-position: -224px -96px;}
.icon136-black {background-image:url('/includes/images/icons-black.png'); background-position: -240px -96px;}
.icon137-black {background-image:url('/includes/images/icons-black.png'); background-position: -256px -96px;}
.icon138-black {background-image:url('/includes/images/icons-black.png'); background-position: -272px -96px;}
.icon139-black {background-image:url('/includes/images/icons-black.png'); background-position: -288px -96px;}
.icon140-black {background-image:url('/includes/images/icons-black.png'); background-position: -304px -96px;}

.icon141-black {background-image:url('/includes/images/icons-black.png'); background-position: 0px -112px;}
.icon142-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px -112px;}
.icon143-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px -112px;}
.icon144-black {background-image:url('/includes/images/icons-black.png'); background-position: -48px -112px;}
.icon145-black {background-image:url('/includes/images/icons-black.png'); background-position: -64px -112px;}
.icon146-black {background-image:url('/includes/images/icons-black.png'); background-position: -80px -112px;}
.icon147-black {background-image:url('/includes/images/icons-black.png'); background-position: -96px -112px;}
.icon148-black {background-image:url('/includes/images/icons-black.png'); background-position: -112px -112px;}
.icon149-black {background-image:url('/includes/images/icons-black.png'); background-position: -128px -112px;}
.icon150-black {background-image:url('/includes/images/icons-black.png'); background-position: -144px -112px;}
.icon151-black {background-image:url('/includes/images/icons-black.png'); background-position: -160px -112px;}
.icon152-black {background-image:url('/includes/images/icons-black.png'); background-position: -176px -112px;}
.icon153-black {background-image:url('/includes/images/icons-black.png'); background-position: -192px -112px;}
.icon154-black {background-image:url('/includes/images/icons-black.png'); background-position: -208px -112px;}
.icon155-black {background-image:url('/includes/images/icons-black.png'); background-position: -224px -112px;}
.icon156-black {background-image:url('/includes/images/icons-black.png'); background-position: -240px -112px;}
.icon157-black {background-image:url('/includes/images/icons-black.png'); background-position: -256px -112px;}
.icon158-black {background-image:url('/includes/images/icons-black.png'); background-position: -272px -112px;}
.icon159-black {background-image:url('/includes/images/icons-black.png'); background-position: -288px -112px;}
.icon160-black {background-image:url('/includes/images/icons-black.png'); background-position: -304px -112px;}

.icon161-black {background-image:url('/includes/images/icons-black.png'); background-position: 0px -128px;}
.icon162-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px -128px;}
.icon163-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px -128px;}
.icon164-black {background-image:url('/includes/images/icons-black.png'); background-position: -48px -128px;}
.icon165-black {background-image:url('/includes/images/icons-black.png'); background-position: -64px -128px;}
.icon166-black {background-image:url('/includes/images/icons-black.png'); background-position: -80px -128px;}
.icon167-black {background-image:url('/includes/images/icons-black.png'); background-position: -96px -128px;}
.icon168-black {background-image:url('/includes/images/icons-black.png'); background-position: -112px -128px;}
.icon169-black {background-image:url('/includes/images/icons-black.png'); background-position: -128px -128px;}
.icon170-black {background-image:url('/includes/images/icons-black.png'); background-position: -144px -128px;}
.icon171-black {background-image:url('/includes/images/icons-black.png'); background-position: -160px -128px;}
.icon172-black {background-image:url('/includes/images/icons-black.png'); background-position: -176px -128px;}
.icon173-black {background-image:url('/includes/images/icons-black.png'); background-position: -192px -128px;}
.icon174-black {background-image:url('/includes/images/icons-black.png'); background-position: -208px -128px;}
.icon175-black {background-image:url('/includes/images/icons-black.png'); background-position: -224px -128px;}
.icon176-black {background-image:url('/includes/images/icons-black.png'); background-position: -240px -128px;}
.icon177-black {background-image:url('/includes/images/icons-black.png'); background-position: -256px -128px;}
.icon178-black {background-image:url('/includes/images/icons-black.png'); background-position: -272px -128px;}
.icon179-black {background-image:url('/includes/images/icons-black.png'); background-position: -288px -128px;}
.icon180-black {background-image:url('/includes/images/icons-black.png'); background-position: -304px -128px;}

.icon181-black {background-image:url('/includes/images/icons-black.png'); background-position: 0px -144px;}
.icon182-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px -144px;}
.icon183-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px -144px;}
.icon184-black {background-image:url('/includes/images/icons-black.png'); background-position: -48px -144px;}
.icon185-black {background-image:url('/includes/images/icons-black.png'); background-position: -64px -144px;}
.icon186-black {background-image:url('/includes/images/icons-black.png'); background-position: -80px -144px;}
.icon187-black {background-image:url('/includes/images/icons-black.png'); background-position: -96px -144px;}
.icon188-black {background-image:url('/includes/images/icons-black.png'); background-position: -112px -144px;}
.icon189-black {background-image:url('/includes/images/icons-black.png'); background-position: -128px -144px;}
.icon190-black {background-image:url('/includes/images/icons-black.png'); background-position: -144px -144px;}
.icon191-black {background-image:url('/includes/images/icons-black.png'); background-position: -160px -144px;}
.icon192-black {background-image:url('/includes/images/icons-black.png'); background-position: -176px -144px;}
.icon193-black {background-image:url('/includes/images/icons-black.png'); background-position: -192px -144px;}
.icon194-black {background-image:url('/includes/images/icons-black.png'); background-position: -208px -144px;}
.icon195-black {background-image:url('/includes/images/icons-black.png'); background-position: -224px -144px;}
.icon196-black {background-image:url('/includes/images/icons-black.png'); background-position: -240px -144px;}
.icon197-black {background-image:url('/includes/images/icons-black.png'); background-position: -256px -144px;}
.icon198-black {background-image:url('/includes/images/icons-black.png'); background-position: -272px -144px;}
.icon199-black {background-image:url('/includes/images/icons-black.png'); background-position: -288px -144px;}
.icon200-black {background-image:url('/includes/images/icons-black.png'); background-position: -304px -144px;}

.icon201-black {background-image:url('/includes/images/icons-black.png'); background-position: 0px -160px;}
.icon202-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px -160px;}
.icon203-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px -160px;}
.icon204-black {background-image:url('/includes/images/icons-black.png'); background-position: -48px -160px;}
.icon205-black {background-image:url('/includes/images/icons-black.png'); background-position: -64px -160px;}
.icon206-black {background-image:url('/includes/images/icons-black.png'); background-position: -80px -160px;}
.icon207-black {background-image:url('/includes/images/icons-black.png'); background-position: -96px -160px;}
.icon208-black {background-image:url('/includes/images/icons-black.png'); background-position: -112px -160px;}
.icon209-black {background-image:url('/includes/images/icons-black.png'); background-position: -128px -160px;}
.icon210-black {background-image:url('/includes/images/icons-black.png'); background-position: -144px -160px;}
.icon211-black {background-image:url('/includes/images/icons-black.png'); background-position: -160px -160px;}
.icon212-black {background-image:url('/includes/images/icons-black.png'); background-position: -176px -160px;}
.icon213-black {background-image:url('/includes/images/icons-black.png'); background-position: -192px -160px;}
.icon214-black {background-image:url('/includes/images/icons-black.png'); background-position: -208px -160px;}
.icon215-black {background-image:url('/includes/images/icons-black.png'); background-position: -224px -160px;}
.icon216-black {background-image:url('/includes/images/icons-black.png'); background-position: -240px -160px;}
.icon217-black {background-image:url('/includes/images/icons-black.png'); background-position: -256px -160px;}
.icon218-black {background-image:url('/includes/images/icons-black.png'); background-position: -272px -160px;}
.icon219-black {background-image:url('/includes/images/icons-black.png'); background-position: -288px -160px;}
.icon220-black {background-image:url('/includes/images/icons-black.png'); background-position: -304px -160px;}

.icon221-black {background-image:url('/includes/images/icons-black.png'); background-position: 0px -176px;}
.icon222-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px -176px;}
.icon223-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px -176px;}
.icon224-black {background-image:url('/includes/images/icons-black.png'); background-position: -48px -176px;}
.icon225-black {background-image:url('/includes/images/icons-black.png'); background-position: -64px -176px;}
.icon226-black {background-image:url('/includes/images/icons-black.png'); background-position: -80px -176px;}
.icon227-black {background-image:url('/includes/images/icons-black.png'); background-position: -96px -176px;}
.icon228-black {background-image:url('/includes/images/icons-black.png'); background-position: -112px -176px;}
.icon229-black {background-image:url('/includes/images/icons-black.png'); background-position: -128px -176px;}
.icon230-black {background-image:url('/includes/images/icons-black.png'); background-position: -144px -176px;}
.icon231-black {background-image:url('/includes/images/icons-black.png'); background-position: -160px -176px;}
.icon232-black {background-image:url('/includes/images/icons-black.png'); background-position: -176px -176px;}
.icon233-black {background-image:url('/includes/images/icons-black.png'); background-position: -192px -176px;}
.icon234-black {background-image:url('/includes/images/icons-black.png'); background-position: -208px -176px;}
.icon235-black {background-image:url('/includes/images/icons-black.png'); background-position: -224px -176px;}
.icon236-black {background-image:url('/includes/images/icons-black.png'); background-position: -240px -176px;}
.icon237-black {background-image:url('/includes/images/icons-black.png'); background-position: -256px -176px;}
.icon238-black {background-image:url('/includes/images/icons-black.png'); background-position: -272px -176px;}
.icon239-black {background-image:url('/includes/images/icons-black.png'); background-position: -288px -176px;}
.icon240-black {background-image:url('/includes/images/icons-black.png'); background-position: -304px -176px;}

.icon241-black {background-image:url('/includes/images/icons-black.png'); background-position: -0px -192px;}
.icon242-black {background-image:url('/includes/images/icons-black.png'); background-position: -16px -192px;}
.icon243-black {background-image:url('/includes/images/icons-black.png'); background-position: -32px -192px;}

/*-------------------------------------------------------*/
	/*NEWS*/
/*-------------------------------------------------------*/
.news {
	margin-top:9px !important;
}
.news-date {
	width:48px;
	height:48px;
	background:url('/includes/images/rounded-bg.png');
	text-align:center;
	margin-right:15px;
	margin-bottom:20px;
}
.news-date .day { margin-top:7px !important; font-size:18px; margin-bottom:0px !important; font-weight:bold;}
.news-date .month { font-size:10px !important; font-style:italic;}
/*-------------------------------------------------------------------------------------------------*/
	/*BUTTONS*/
/*-------------------------------------------------------------------------------------------------*/	

a.btn	{	
	display: inline-block; 
	margin: 0 5px 7px 5px;
	padding:10px;
	color: #ffffff;	
}

a.btn1	{	
	display: inline-block; 
	margin: 0 5px 7px 5px;
	padding:10px;
	color: #292929;	
}

a.btn3	{	
	display: inline-block; 
	margin: 0 5px 7px 5px;
	padding:10px;
	color: #66666;	
}

.tab01a	{	-moz-border-radius: 10px 10px 10px 0;	-webkit-border-radius: 10px 10px 10px 0;	border-radius: 10px 10px 10px 0;	}
.tab01b	{	-moz-border-radius: 10px 10px 0 10px;	-webkit-border-radius: 10px 10px 0 10px;	border-radius: 10px 10px 0 10px;	}
.tab01c	{	-moz-border-radius: 10px 0 10px 10px;	-webkit-border-radius: 10px 0 10px 10px;	border-radius: 10px 0 10px 10px;	}
.tab01d	{	-moz-border-radius: 0 10px 10px 10px;	-webkit-border-radius: 0 10px 10px 10px;	border-radius: 0 10px 10px 10px;	}

.tab02a	{	-moz-border-radius: 10px 10px 0 0;	-webkit-border-radius: 10px 10px 0 0;	border-radius: 10px 10px 0 0;	}
.tab02b	{	-moz-border-radius: 0 0 10px 10px;	-webkit-border-radius: 0 0 10px 10px;	border-radius: 0 0 10px 10px;	}
.tab02c	{	-moz-border-radius: 10px 0 0 10px;	-webkit-border-radius: 10px 0 0 10px;	border-radius: 10px 0 0 10px;	}
.tab02d	{	-moz-border-radius: 0 10px 10px 0;	-webkit-border-radius: 0 10px 10px 0;	border-radius: 0 10px 10px 0;	}

.tab03a	{	-moz-border-radius: 10px 0 0 0;	-webkit-border-radius: 10px 0 0 0;	border-radius: 10px 0 0 0;	}
.tab03b	{	-moz-border-radius: 0 10px 0 0;	-webkit-border-radius: 0 10px 0 0;	border-radius: 0 10px 0 0;	}
.tab03c	{	-moz-border-radius: 0 0 10px 0;	-webkit-border-radius: 0 0 10px 0;	border-radius: 0 0 10px 0;	}
.tab03d	{	-moz-border-radius: 0 0 0 10px;	-webkit-border-radius: 0 0 0 10px;	border-radius: 0 0 0 10px;	}

.tab04a	{	-moz-border-radius: 10px 0;	-webkit-border-radius: 10px 0;	border-radius: 10px 0;	}
.tab04b	{	-moz-border-radius: 0 10px;	-webkit-border-radius: 0 10px;	border-radius: 0 10px;	}



.btn.grey	{
	background-color: #666666;
}
	a:hover.btn.grey	{	
		background-color: #191919;
		text-decoration:none;
	}

.btn.black	{
	background-color: #000000;
}
	a:hover.btn.black	{	
		background-color: #212121;
		text-decoration:none;
	}

.btn1.grey	{
	background-color: #e1e1e1;
}
	a:hover.btn1.grey	{	
		background-color: #e7e7e7;
		text-decoration:none;
	}
	
.btn3.white	{
	background-color: #ededed;
}
	a:hover.btn3.white	{	
		background-color: #e7e7e7;
		text-decoration:none;
	}


/*-------------------------------------------------------------------------------------------------*/
	/*PAGINATION */
/*-------------------------------------------------------------------------------------------------*/
.pagination {
		list-style:none;
	}
	.pagination li {
		display:inline;
		padding-top:20px;
	}
	.pagination li a {
		font-size:11px;
		display:block;
		float:left;
		padding:0 5px;
		margin-right:7px;
		background:#ffffff;
		text-decoration:none;
		text-shadow:none;
		border:1px solid #ededed;
		border-radius: 3px;
		-webkit-border-radius: 3px;
		-moz-border-radius: 3px;
	}
	.pagination li.current a {
		background-color:#000000;
		color:#ffffff;
		border:1px solid #000000;
	}
	.pagination li a:hover {
		background-color:#000000;
		color:#ffffff;
		border:1px solid #000000;
	}
	.pagination li.disabled { cursor: not-allowed; }
/*-------------------------------------------------------------------------------------------------*/
	/*LISTS*/
/*-------------------------------------------------------------------------------------------------*/

.check-list {
	font-size:11px;
	list-style-type:none;
	list-style-position:outside;
}
.check-list li {
	margin:0px;	
	display:block;
	padding:6px 0px 6px 35px;
	background: url(/includes/images/check.png) no-repeat;
	background-position:left center;
	font-style:italic;
	border-bottom:1px dotted #dedede;
}
.info-list {
	font-size:12px;
	list-style-type:none;
	list-style-position:outside;
}
.info-list li {
	margin:0px;	
	display:block;
	padding:11px 0px 11px 35px;
	background: url(/includes/images/info.png) no-repeat;
	background-position:left center;
	font-style:italic;
}
.cancel-list {
	font-size:12px;
	list-style-type:none;
	list-style-position:outside;
}
.cancel-list li {
	margin:0px;	
	display:block;
	padding:11px 0px 11px 35px;
	background: url(/includes/images/cancel.png) no-repeat;
	background-position:left center;
	font-style:italic;
}
.question-list {
	font-size:12px;
	list-style-type:none;
	list-style-position:outside;
}
.question-list li {
	margin:0px;	
	display:block;
	padding:11px 0px 11px 35px;
	background: url(/includes/images/question.png) no-repeat;
	background-position:left center;
	font-style:italic;
}
.warning-list {
	font-size:12px;
	list-style-type:none;
	list-style-position:outside;
}
.warning-list li {
	margin:0px;	
	display:block;
	padding:11px 0px 11px 35px;
	background:url(/includes/images/warning.png) no-repeat;
	background-position:left center;
	font-style:italic;
}
.arrow-list {
	font-size:12px;
	list-style-type:none;
	list-style-position:outside;
}
.arrow-list li{
	margin:0px;	
	display:block;
	padding:11px 0px 11px 35px;
	background: url(/includes/images/list-arrow.png) no-repeat;
	background-position:left center;
	font-style:italic;
}

.list .dot-sep{
		background-image:url('/includes/images/dot-sep.png');
		height:2px;
		background-repeat:repeat-x;
}

/*-------------------------------------------------------------------------------------------------*/
	/*TABLES */
/*-------------------------------------------------------------------------------------------------*/

table.tablesorter {
	font-family:arial;
	background-color: #f9f9f9;
	margin:10px 0pt 15px;
	font-size: 8pt;
	width: 100%;
	text-align: left;
}
table.tablesorter thead tr th, table.tablesorter tfoot tr th {
	background-color: #f9f9f9;
	border: 1px solid #ededed;
	font-size: 8pt;
	padding: 4px;
}
table.tablesorter thead tr .header {
	background-image: url('/includes/images/bg.gif');
	background-repeat: no-repeat;
	background-position: center right;
	cursor: pointer;
}
table.tablesorter tbody td {
	padding: 4px;
	vertical-align: top;
}
table.tablesorter tbody tr.odd td {
	background-color:#333333;
}
table.tablesorter thead tr .headerSortUp {
	background-image: url('/includes/images/asc.gif');
}
table.tablesorter thead tr .headerSortDown {
	background-image: url('/includes/images/desc.gif');
}
table.tablesorter thead tr .headerSortDown, table.tablesorter thead tr .headerSortUp {
background-color: #ededed;
}

table.tablesorter tr:nth-child(odd) { background-color: #ffffff; }
table.tablesorter tr:nth-child(even) { background-color: #ededed; }
table.tablesorter tr:hover { background-color: #cecece; }

/*-------------------------------------------------------------------------------------------------*/
	/*TABS */
/*-------------------------------------------------------------------------------------------------*/

.section {
	background: #f9f9f9;
}
ul.tabs {
	height: 28px;
	line-height: 25px;
	list-style: none;
	border-bottom: 1px solid #DDD;
	background: #f9f9f9;
}
.tabs li {
	float: left;
	display: inline;
	margin: 0 1px -1px 0;
	padding: 0 13px 1px;
	cursor: pointer;
	background: #F9F9F9;
	border: 1px solid #e9e9e9;
	border-bottom: 1px solid #f9f9f9;
	position: relative;
	color:#333333;
}
.tabs li:hover,
.vertical .tabs li:hover {
	padding: 0 13px;
	background: #ededed;
	border: 1px solid #e4e4e4;
}
.tabs li.current {
	background: #f3f3f3;
	padding: 0 13px 2px;
	border: 1px solid #d4d4d4;
	border-bottom: 1px solid #f3f3f3;
}
.box {
	display: none;
	border: 1px solid #D4D4D4;
  	border-width: 0 1px 1px;
	background: #f3f3f3;
	padding-top:20px;
	padding-left:10px;
	padding-right:10px;
	margin-bottom:30px;
}
.box.visible {
	display: block;
}
.section.vertical {
	border-left: 160px solid #f9f9f9;
}
.vertical .tabs {
	width: 160px;
	float: left;
	display: inline;
	margin: 0 0 0 -160px;
}
.vertical .tabs li {
	padding: 0 13px;
	padding-top:10px;
	margin: 0 0 1px;
	border: 1px solid #E4E4E4;
	border-right: 1px solid #F9F9F9;
	width: 132px;
	height: 33px;
}
.vertical .tabs li:hover {
	padding: 0 13px;
	padding-top:10px;
	margin: 0 0 1px;
	border: 1px solid #E4E4E4;
	border-right: 1px solid #F9F9F9;
	width: 131px;
	height: 33px;
}
.vertical .tabs li.current {
	width: 133px;
	color: #444;
	background: #f3f3f3;
	border: 1px solid #D4D4D4;
	border-right: 1px solid #f3f3f3;
	margin-right: -1px;
}
.vertical .box {
  border-width: 1px;
  padding-top:15px;
}
/*-------------------------------------------------------------------------------------------------*/
	/*SOCIAL MEDIA ICONS */
/*-------------------------------------------------------------------------------------------------*/

.tweet-icon {
	height:26px;
	width:26px;
	background-image:url('/includes/images/social/t.png');
	background-position: -0px -0px;
	float:left;
	margin-top:8px;
	margin-right:10px;
}
	.tweet-icon:hover {
		height:26px;
		width:26px;
		background-image:url('/includes/images/social/t.png');
		background-position: -0px -26px;
	}

.facebook-icon {
	height:26px;
	width:26px;
	background-image:url('/includes/images/social/f.png');
	background-position: -0px -0px;
	float:left;
	margin-top:8px;
	margin-right:10px;
}
	.facebook-icon:hover {
		height:26px;
		width:26px;
		background-image:url('/includes/images/social/f.png');
		background-position: -0px -26px;
	}

.google-icon {
	height:26px;
	width:26px;
	background-image:url('/includes/images/social/g.png');
	background-position: -0px -0px;
	float:left;
	margin-top:8px;
	margin-right:10px;
}
	.google-icon:hover {
		height:26px;
		width:26px;
		background-image:url('/includes/images/social/g.png');
		background-position: -0px -26px;
	}

.vimeo-icon {
	height:26px;
	width:26px;
	background-image:url('/includes/images/social/v.png');
	background-position: -0px -0px;
	float:left;
	margin-top:8px;
	margin-right:10px;
}
	.vimeo-icon:hover {
		height:26px;
		width:26px;
		background-image:url('/includes/images/social/v.png');
		background-position: -0px -26px;
	}
	
.dribbble-icon {
	height:26px;
	width:26px;
	background-image:url('/includes/images/social/d.png');
	background-position: -0px -0px;
	float:left;
	margin-top:8px;
	margin-right:10px;
}
	.dribbble-icon:hover {
		height:26px;
		width:26px;
		background-image:url('/includes/images/social/d.png');
		background-position: -0px -26px;
	}
/*-------------------------------------------------------------------------------------------------*/
	/*BLOG */
/*-------------------------------------------------------------------------------------------------*/

.meta {
	margin-right:20px;
	margin-left:5px;
	margin-bottom:15px;
	font-size:10px;
	float:left;
}
.meta2 {
	margin-right:20px;
	margin-bottom:15px;
	font-size:10px;
	float:left;
}
.meta-right {
	margin-right:0px;
	margin-left:5px;
	margin-bottom:15px;
	font-size:10px;
	float:right;
}
.blog .icon-white-big { background-color:#000000;}
.blog h3 { margin-bottom:13px;}
.blog h4 { line-height:24px;}
/*-------------------------------------------------------------------------------------------------*/
	/*SIDEBAR */
/*-------------------------------------------------------------------------------------------------*/

/*Start Search Form*/
	#search-form input{height:30px; line-height:30px; padding:0 10px; font-size:11px; border:1px solid #e9e9e9; width:240px; color:#777777; background-color:#ffffff;}
	.side-bar4col #search-form input{height:30px; line-height:30px; padding:0 10px; font-size:11px; border:1px solid #e9e9e9; width:170px; color:#777777; background-color:#ffffff;}
	.side-bar4col-right #search-form input{height:30px; line-height:30px; padding:0 10px; font-size:11px; border:1px solid #e9e9e9; width:170px; color:#777777; background-color:#ffffff;}
	/*End Searhc Form*/

/*-------------------------------------------------------*/
	/*FORMS*/
/*-------------------------------------------------------*/
label {
	width:200px;
	font-weight:normal;
	text-transform:uppercase;
	padding-bottom:5px;
	display:block;
}
.form { margin-top:15px;}

input[type=text],input[type=password],input.text,input.title,textarea,input[type=email] {
	background-color:#FFF;
	border:1px solid #e1e1e1;
	font-size:11px;
}
input[type=text]:focus,input[type=password]:focus,input.text:focus,input.title:focus,textarea:focus,input[type=email]:focus {
	border-color:#d7d7d7;
	-moz-box-shadow: 0 0px 2px #d7d7d7;
	-webkit-box-shadow: 0 0px 2px #d7d7d7;
	box-shadow: 0 0px 2px #d7d7d7;
}
select {
	background-color:#fff;
	border-width:1px;
	border-style:solid;
}
input[type=text],input[type=password],input.text,input.title,textarea,select,input[type=email] {
}
input.text,input.title {
	width:290px;
	padding:5px;
	background:#ffffff;
}
input.texts {
	width:610px;
	padding:5px;
	background:#ffffff;
}
input.title {
	font-size:1.5em;
}
textarea {
	width:610px;
	height:180px;
	padding:5px;
	background:#ffffff;
}
form.inline {
	line-height:3;
}
form.inline p {
	margin-bottom:0;
}
.required {
	color:#ff0000;
}
.form { margin-top:15px !important;}
.button{
		cursor:pointer;
		font-size: 11px;
		color: #ffffff;
		padding: 6px 15px;
		margin-top:15px;
		background-color:#323232;	
		border: 1px solid #323232;
	}
	.button:hover {
		color:#FFF;
		background:#393b3f;
	}

.notification_error
{
border: 1px solid #ededed;
height: auto;
padding: 4px;
background: #f9f9f9;
text-align: left;
margin-bottom:10px;
color:red;
}
 
.notification_ok
{
border: 1px #ededed solid;
height: auto;
padding: 8px;
background: #f9f9f9;
text-align: center;
color: green;
}
/*-------------------------------------------------------------------------------------------------*/
	/*TIPSY */
/*-------------------------------------------------------------------------------------------------*/

.tipsy { padding: 5px; font-size: 10px; opacity: 1; background-repeat: no-repeat;  background-image: url(/includes/images/tipsy.gif); }
.tipsy-inner { padding: 6px 9px 5px 9px; background-color: #2d3035; color: #ededed; text-shadow:1px 1px #393b3f; max-width: 200px; text-align: center; -moz-border-radius: 5px 5px 5px 5px; -webkit-border-radius: 5px 5px 5px 5px; border-radius: 5px 5px 5px 5px; }
.tipsy-inner { -moz-border-radius:3px; -webkit-border-radius:3px; }
.tipsy-north { background-position: top center; }
.tipsy-south { background-position: bottom center; }
.tipsy-east { background-position: right center; }
.tipsy-west { background-position: left center; }

.footer .flickr { margin-right:10px;}
.footer .item a{ padding:3px;}



/*-------------------------------------------------------------------------------------------------*/
	/*BLOCKQUOTES*/
/*-------------------------------------------------------------------------------------------------*/

.blockquote1 {
	padding-left:20px;
	border-left:1px solid;
}
.blockquote2 {
	padding-left:20px;
	border-left:1px dotted;
}
.blockquote3 {
	padding-left:20px;
	padding-right:20px;
	border-left:2px  dashed;
	border-right:2px dashed;
}
.blockquote4 {
	border-top:1px dotted;
	padding-top:10px;
	padding-bottom:10px;
	border-bottom:1px dotted;
}
.blockquote5 {
	padding:10px;
	border:1px solid;
}
.blockquote6 {
	padding-left:70px;
	background-image:url('/includes/images/blockquote6.png');
	background-repeat:no-repeat;
	background-position: left;
}
.blockquote7 {
	padding-left:70px;
	background-image:url('/includes/images/blockquote7.png');
	background-repeat:no-repeat;
	background-position: left;
}
.blockquote8 {
	padding-left:70px;
	background-image:url('/includes/images/blockquote8.png');
	background-repeat:no-repeat;
	background-position: left;
}
.blockquote9 {
	padding-left:70px;
	background-image:url('/includes/images/blockquote9.png');
	background-repeat:no-repeat;
	background-position: left;
}
/*-------------------------------------------------------------------------------------------------*/
	/*DROPCAPS*/
/*-------------------------------------------------------------------------------------------------*/

.dropcap{
float: left;
font-size: 36px;
margin: 10px 6px 1px 0;
}
.dropcap2 {
border-radius: 30px 30px 30px 30px;
-moz-border-radius:30px;
-webkit-border-radius:30px;
-o-border-radius:30px;
text-shadow:1px 1px #393b3f;
background-color:#393b3f;
color: #FFFFFF;
display: block;
float: left;
font-size: 25px;
height: 20px;
margin: 5px 10px 0 0;
padding: 13px 10px 13px 12px;
text-align: center;
vertical-align: bottom;
width: 25px;
}

.dropcap3 {
background-color:#393b3f;
color: #FFFFFF;
text-shadow:1px 1px #393b3f;
display: block;
float: left;
font-size: 25px;
height: 20px;
margin: 5px 10px 0 0;
padding: 13px 10px 13px 12px;
text-align: center;
vertical-align: bottom;
width: 25px;
}

.dropcap4 {
border-radius: 30px;
-moz-border-radius:30px;
-webkit-border-radius:30px;
-o-border-radius:30px;
background-color:#ededed;
color: #393b3f;
display: block;
float: left;
font-size: 25px;
height: 20px;
margin: 5px 10px 0 0;
padding: 13px 10px 13px 12px;
text-align: center;
vertical-align: bottom;
width: 25px;
}

.dropcap5 {
background-color:#ededed;
color: #393b3f;
display: block;
float: left;
font-size: 25px;
height: 20px;
margin: 5px 10px 0 0;
padding: 13px 10px 13px 12px;
text-align: center;
vertical-align: bottom;
width: 25px;
}


/*-------------------------------------------------------------------------------------------------*/
	/*HIGHLIGHT*/
/*-------------------------------------------------------------------------------------------------*/

span.highlight{
  background:#FFFF99;
  color:#393b3f;
  text-shadow:1px 1px #ffffff;
}

span.highlight-blue{
  background:#0099CC;
  text-shadow:1px 1px #393b3f;
}

span.highlight-red{
  background:#CC0033;
  text-shadow:1px 1px #393b3f;
}

span.highlight-green{
  background:#339933;
  text-shadow:1px 1px #393b3f;
}

span.highlight-purple{
  background:#CC33CC;
  text-shadow:1px 1px #393b3f;
}

span.highlight-orange{
  background:#FF9933;
  text-shadow:1px 1px #393b3f;
}

span.highlight-brown{
  background:#660000;
  text-shadow:1px 1px #393b3f;
}

span.highlight-grey{
  background:#999999;
  text-shadow:1px 1px #393b3f;
}


span.highlight-blue,span.highlight-red,span.highlight-green,span.highlight-purple,span.highlight-orange,span.highlight-brown,span.highlight-grey{
  color:#FFFFFF
}

span.highlight,span.highlight-blue,span.highlight-red,span.highlight-green,span.highlight-purple,span.highlight-orange,span.highlight-brown,span.highlight-grey{
  padding:1px 5px;
}

/*-------------------------------------------------------------------------------------------------*/
/* DEMO ONLY */
/* ----------------------------------------- */
.slide-out-div {
       padding: 20px 10px 0 20px;
       width: 180px;
       background-color: #000000;
       position: relative;
       z-index: 999;
       font-size: 11px;
}
#colorpicker-body, #colorpicker-wrapper, #colorpicker-headers, #colorpicker-links, #colorpicker-text, #colorpicker-prev, #colorpicker-black{
	height:16px;
	background-image: url('/includes/images/colorpicker/select3.png');
	background-repeat:no-repeat;
	padding-top:1px;
	padding-left:21px;
}
#colorpicker {
	height:16px;
	background-image: url('/includes/images/colorpicker/select3-icon.png');
	background-repeat:no-repeat;
	padding-top:1px;
	padding-left:21px;
}
.slide-out-div p {
       font-size: 10px;
       line-height: 14px;
}



.slide-out-div ul {
	margin-bottom:40px;
	padding:0px;
}


.slide-out-div ul li {
       list-style-type: circle;
       list-style-position: inside;
	   margin-top:0px;
}

.slide-out-div ul li a {
       color:#888;
       font-size: 11px;
	   margin:0px;
}

.slide-out-div ul li a:hover {
       color:#dfdfdf;
}

.slide-out-div ul.last li {
       float:left;
       width: 85px;
       margin-bottom: 0px;
}

.slide-out-div ul.last li a {
       cursor: pointer;
}

.slide-out-div ul.color-switcher {
	margin-bottom:40px;
}

.slide-out-div ul.color-switcher li {
       list-style: none;
       float:left;
     
}

.slide-out-div ul.color-switcher li a {
       display: block;
       width: 15px;
       height: 15px;
       text-indent: -99999px;
       margin-right: 7px;
       cursor: pointer;
}

.slide-out-div h3 {
       color: #ffffff !important;
       font-size: 15px;
	   text-shadow:none;
}
#style-switcher {  
  position: absolute;  
  width: 55px;  
  top: 100px;  
  left: 5px;  
  background: #f3f3f3;
  padding: 10px;
  border: 1px solid #ffffff;     
} 	
.color-box {
	width:15px;
	height:15px;
	display:block;
	float:left;
	margin-right:2px;
	margin-left:2px;
	margin-bottom: 5px;
	border: 1px solid #cacaca;
	background:#ffffff;
}
.pattern-box{
	width:12px;
	height:12px;
	display:block;
	float:left;
	margin-right:2px;
	margin-left:2px;
	margin-bottom: 5px;
	border: 1px solid #cacaca;
	background:#ffffff;
}
.slide-out-div h3 {
	margin-bottom:10px;
	margin-top:10px;
	line-height:15px;
}
.slide-out-div div{
	margin-top:10px;
	color:#ffffff !important;
}
#switcher-reset {
	background-image: url('/includes/images/colorpicker/reset.png');
	height:27px;
	width:82px;
	text-align:center;
	padding-top:8px;
	background-repeat:no-repeat;
}

table { width: 100%; }
.center { width: 20%; margin: 0 auto; }
