
<?php foreach($this->posts as $post) { 
	$user = new Default_Model_User();
	$select = new Zend_Db_Table_Select($user);
	$select->where('id = ?', $post->forum_post_user_id);
	$user = $user->fetchRow($select);
	?>
	<div class='post'>
	<div class='title'><h3><?php echo stripslashes($post['forum_post_title']); ?></h3></div>
	<div class='content'><?php echo stripslashes($post['forum_post_content']); ?></div>
	<div class='user'><h4><?php echo stripslashes($user->user_screen_name);?></h4>
	<div id='newPostLink'><a href='/forum/newreply/?cid=<?php echo $_GET['cid']; ?>&id=<?php echo $_GET['id']; ?>'>New Reply</a><br /><?php echo Bootstrap::getUser() == $user->id ? "<a href='/forum/editpost/?cid=".$_GET['cid']."&id=".$post->id."'>Edit Post</a>" : ""; ?><br /><?php echo Bootstrap::getUser() == $user->id ? "<a href='/forum/deletepost/?cid=".$_GET['cid']."&id=".$post->id."'>Delete Post</a>" : ""; ?></div></div>
	<div class='signature'><?php echo $user->user_signature; ?></div>
	</div>
<?php } ?>