<?php
$items = $this->items;

$sections = array();
foreach($items as $item) {
	$section = $item->template_section;
	$sections[$section][] = $item;
		
}
foreach($sections as $section=>$items) { 
	if($section != 'custom') {	?>
	<h3><?=ucwords($section)?></h3>
	<p>
		<?php foreach($items as $item) { ?>
		<div id='item'>
			<div class='left'><?=$item->template_display;?></div>
			<div class='right'><input value="<?=str_replace("\"","'",stripslashes($item->template_current_value))?>" type='text' onkeyup='changeStyle("<?=$item->id?>",this.value)'/></div>
			<div class='clear'></div>
		</div>
		<?php } } ?>
	</p>
	<br />	
<?php
}
$custom = Bootstrap::getDataS('template','template_section = "custom"');
?>
<h3>Custom CSS</h3>
<p>
	<div id='item'>
    	<div class='left'>Put in your custom CSS here</div>
        <div class='right'><textarea id='custom_css' value="<?=str_replace("\"","'",stripslashes($custom->template_current_value))?>" onkeyup='changeStyle("<?=$custom->id?>",this.value)'><?=str_replace("\"","'",stripslashes($custom->template_current_value))?></textarea></div>
    </div>
</p>
<script type='text/javascript'>
function changeStyle(id, value) {
	new Ajax.Request('/template/edit/', {
		method:  'post',
		parameters: { id : id, value: value },
		onSuccess: function() {
			<?php if(Bootstrap::isInGroup('administrator')) { ?>
			$j('link[href="/css/layout"]').attr('href','/css/layout');
			<?php } ?>
		}
	});
}
</script><div class='clear'></div>