<?php
if(isset($this->form)) {
$_f = $this->form;
?>
<div class="page_head">
    <h3><?php echo str_replace("_"," ",$_f->getName()); ?></h3>
</div>
<br/>
        <form action="<?php echo $_f->getAction(); ?>"
                method="<?php echo $_f->getMethod(); ?>"
                id="form-validate"
        >
                <?php
                $groups = $_f->getDisplayGroups();
                foreach($groups as $group) {
                ?>
                        <fieldset class="fields regField <?php echo $group->getAttrib('class'); ?>">
                            <legend>
                                                <?php echo $group->getLegend(); ?>
                            </legend>
                                        
                                        <?php
                                        $elements = $group->getElements();
                                        foreach($elements as $element) { ?>
                                                        <?php echo $element->render(); ?>
                                        <div class="clear"></div>
                                        <?php
                                        }
                                        ?>
                        </fieldset>
            <?php
                }
                ?>
            <br/>
        <div class="back_button" onClick="history.go(-1)" >Back</div>
        <div class="save_button" onClick='$j("#form-validate").submit()' >Save</div>
    <div class="clear"></div>
</form>

<?php } ?>
<?php

/* @TODO @TODO @TODO

<form <?php foreach($attribs as $key=>$value) { echo "$key='$value' "; } ?>>
	<div id="blog_post_image">
		<p>Current Image (if any):</p><br />
		<img src="<?=$page->image;?>" /><br />
		<?=$page->image;?><br /><br />
	</div>
	<div class="clear"></div>
    <?php
    $groups = $_f->getDisplayGroups();
    foreach($groups as $group) {
    ?>
		<fieldset class="<?php echo $group->getAttrib('class'); ?>">
			<legend><?php echo ucwords($group->getLegend()); ?></legend>
			<div section="<?=$group->getAttrib('id');?>">
	            <?php
	            $elements = $group->getElements();
	            foreach($elements as $element) { ?>
	               <div section='<?=$element->getName()?>'>

		 	           <?php echo $element->render(); ?>
		               <div class="clear"></div>
		           </div>
	            <?php } ?>
	        </div>
        </fieldset>
    <?php }?>
    <br/>
</form>

*/
