<style type="text/css">
	form#login_form input { margin: 20px auto; display: block; }
	.loader { text-align: center; height: 120px;  } .loader span { display: inline-block; vertical-align: middle; width: 5px; height: 5px; margin: 50px auto; background: black; border-radius: 50px; -webkit-animation: loader 0.9s infinite alternate; -moz-animation: loader 0.9s infinite alternate; }  .loader span:nth-of-type(2) { -webkit-animation-delay: 0.3s; -moz-animation-delay: 0.3s; }      .loader span:nth-of-type(3) { -webkit-animation-delay: 0.6s; -moz-animation-delay: 0.6s; }      @-webkit-keyframes loader { 0% { width: 5px; height: 5px; opacity: 0.9; -webkit-transform: translateY(0); } 100% { width: 15px; height: 15px; opacity: 0.1; -webkit-transform: translateY(-21px); } }   @-moz-keyframes loader { 0% { width: 5px; height: 5px; opacity: 0.9; -moz-transform: translateY(0); } 100% {width: 15px; height: 15px; opacity: 0.1; -moz-transform: translateY(-21px); } }
</style>
<div class="slogan">
	<div class="span-24">
		<h2 class="link">Administrative Login</h2>
		<h4 class="em">Use the form below to log in to the Admin Panel.</h4>
	</div>
</div>
<div class="span-24 separator"></div>
<div class="clear clearfix"></div>
<!-- Login Form -->
<form id='login_form' class="clearfix" action="/user/login/" method="post" style="margin-top: -5.5em;">
	<?php 
	 if(isset($_REQUEST['demo'])) { ?>
     Welcome to the Demo User Login. Login with the following credentials.<br /><br />Username: <strong>demo</strong><br />Password: <strong>demouser</strong><?php } ?>
    <?php $error = !empty($_SESSION['msg']['login-err']) ? $_SESSION['msg']['login-err'] : null; ?><br /><br />
    <fieldset class='fields login'>
        <?php 
        //This will output login errors, if any
        if ($error) {
            echo '<div class="err">'.$error.'</div>';
            unset($error);
        }
        ?>
        <input type="text" name="username" id="username" value="" size="23" placeholder="Username"/>
        
        
        <input type="password" name="password" id="password" size="23" placeholder="Password" onkeypress="javascript:entersubmit(event)"/>
        
	<a onclick="jQuery('form').submit()" class="button">Login</a>
    </fieldset>
</form>
<div class="loader" style="display: none;"><span></span><span></span><span></span></div>
<script type='text/javascript'>
jQuery(function() {
	jQuery('form#login_form').on('submit', function(e) {
		jQuery('form#login_form').hide();
		jQuery('div.loader').show();
		e.preventDefault();
		var data = jQuery(this).serialize();
		jQuery.post(
			jQuery(this).attr('action')
			, data
			, function(data)
			{
				console.log(data);
				window.location.href = data;
			}
		);


	});
});
function entersubmit(e){

	var eKey=(e.keyCode ? e.keyCode : e.which);
	
	if(eKey==13){
		jQuery("#login_form").submit();
	}
}
</script>
