<?php 

if($_f = $this->form) {
	?>
	<br /><br />
To begin please enter a valid email address and your name below. You are creating an account that will track your progress throught the quote form and allow us to save it for you. At the end we will give you a link that you may access anytime for the next month.
<br /><br />
	<br/>
	        <form action="<?php echo $_f->getAction(); ?>"
	                method="<?php echo $_f->getMethod(); ?>"
	                id="form-validate"
	        >
	                <?php
	                $groups = $_f->getDisplayGroups();
	                foreach($groups as $group) {
	                ?>
	                        <fieldset class="fields regField <?php echo $group->getAttrib('class'); ?>">
	                            <legend>
	                                                <?php echo $group->getLegend(); ?>
	                            </legend>
	                                        
	                                        <?php
	                                        $elements = $group->getElements();
	                                        foreach($elements as $element) { ?>
	                                                        <?php echo $element->render(); ?>
	                                        <div class="clear"></div>
	                                        <?php
	                                        }
	                                        ?>
	                        </fieldset>
	            <?php
	                }
	                ?>
	            <br/>
	</form>
<?php }
else {
$pass = $this->password;
$user = $this->email;
?>
<div class="passWrap">
Write this password down, if you leave this site for an extended period of time, you will loose the form, and we don't want that.
<div class="password"><?=$pass?></div>
<div class="continueLink">
	<form action='/user/login/?quote' method='post'>
		<input type='hidden' value='<?=$user?>' name='username'/>
		<input type='hidden' value='<?=$pass?>' name='password'/>
		<input type='submit' value='Continue'/>
	</form>
</div>
</div>
<?php } ?>
