<?php
$_f = $this->pageForm;
?>
<div class="section vertical" id='comment_form_wrap'>
	<form action="<?php echo $_f->getAction(); ?>"
                method="<?php echo $_f->getMethod(); ?>"
                id="form-validate"
        >
		<ul class="tabs">
                <?php
		$i = 0;
                $groups = $_f->getDisplayGroups();
                foreach($groups as $group) {
			$cur = $i++ < 1 ? ' class="current"' : '';
			echo "<li{$cur}>" . ucwords($group->getLegend()) . "</li>";
		}
                ?>
		</ul>
		
		<?php
		$i = 0;
                foreach($groups as $group) {
                ?>
                        <div class="box <?= $i++ < 1 ? 'visible' : ''?>"> 
				<?php $elements = $group->getElements(); foreach($elements as $element) { ?>
					<div section='<?=$element->getName()?>'>
						<?php echo $element->render(); ?>
						<div class="clear"></div>
					</div>
				<?php } ?>
                        </div>
            <?php } ?>
            <br/>
	</form>
</div>
<div class="clearfix clear"></div>
