<script type='text/javascript'>
	jQuery(function() {
		jQuery.post(
			'/admin/config/',
			function(data) {
				jQuery('#config').html(data);
				(function($) {
					$(function() {
						$('ul.tabs').delegate('li:not(.current)', 'click', function() {
							$(this).addClass('current').siblings().removeClass('current')
							.parents('div.section').find('div.box').hide().eq($(this).index()).fadeIn(150);
						})
					})
				})(jQuery)
			}
		);
	});
</script>
<div class="clearfix clear"></div>
<div id="config" style="padding: 20px 5px;"></div>
<div class="span-24 separator-double"></div>
<div class="clearfix clear"></div>
<br />
<?php
if(class_exists('GoogleAnalytics')) {
$visits = $this->visits;
$views = $this->views;

$views = explode(',',$views);
$visits = explode(',',$visits);

?><script type="text/javascript"> 
addLoadEvent(function() {
	var data = new google.visualization.DataTable();
	data.addColumn('date', 'Date');
	data.addColumn('number', 'Visits');
	data.addColumn('number', 'Page Views');
	<?php
	echo "\tdata.addRows(".count($views).");\n";
	$i = 0;
	foreach($views as $view) {
		$view = explode('-',$view);
		$date = $view[0];
		$year = (int)substr($date,0,4);
		$month = (int)substr($date,4,2);
		$day = (int)substr($date,6,2);
		$data = (int)$view[1];
		if($data > 1) {
			echo "\tdata.setValue($i, 0, new Date($year, $month-1, $day));\n";
			echo "\tdata.setValue(".$i++.", 1, ".$data.");\n";
		}
	}
	$i = 0;
	foreach($visits as $visit) {
		$visit = explode('-',$visit);
		$data = (int)$visit[1];
		if($data > 1) {
			echo "\tdata.setValue(".$i++.", 2, ".$data.");\n";
		}
	}
	?>
	var annotatedtimeline = new google.visualization.AnnotatedTimeLine(document.getElementById('ga'));
	annotatedtimeline.draw(data, {allowRedraw: true});
	jQuery('#ga').css('height','475px');
	
	
});
</script>
<?php } ?>
<div id="ga" style='width: 940px; height:500px;'></div><br /><br />
