<?php
if(class_exists('GoogleAnalytics')) {
$visits = $this->visits;
$views = $this->views;

$views = explode(',',$views);
$visits = explode(',',$visits);

?><script type="text/javascript"> 
addLoadEvent(function() {
	var data = new google.visualization.DataTable();
	data.addColumn('date', 'Date');
	data.addColumn('number', 'Visits');
	data.addColumn('number', 'Page Views');
	<?php
	echo "\tdata.addRows(".count($views).");\n";
	$i = 0;
	foreach($views as $view) {
		$view = explode('-',$view);
		$date = $view[0];
		$year = (int)substr($date,0,4);
		$month = (int)substr($date,4,2);
		$day = (int)substr($date,6,2);
		$data = (int)$view[1];
		if($data > 1) {
			echo "\tdata.setValue($i, 0, new Date($year, $month-1, $day));\n";
			echo "\tdata.setValue(".$i++.", 1, ".$data.");\n";
		}
	}
	$i = 0;
	foreach($visits as $visit) {
		$visit = explode('-',$visit);
		$data = (int)$visit[1];
		if($data > 1) {
			echo "\tdata.setValue(".$i++.", 2, ".$data.");\n";
		}
	}
	?>
	var annotatedtimeline = new google.visualization.AnnotatedTimeLine(document.getElementById('ga'));
	annotatedtimeline.draw(data, {allowRedraw: true});
	$j('#ga').css('height','475px');
	
	
});
</script>
<?php }
if(Bootstrap::isInGroup('administrator')) { ?>
<script type='text/javascript'>
	addLoadEvent(function() {
		new Ajax.Updater('config','/admin/config');
	});
</script>
<?php } ?>
<div id="admin_dashboard">
	<?php 
	if(Bootstrap::isInGroup('administrator')) { ?>
		<a href="#" onclick="$j('#config').toggle('slow');" >Site Configuration</a> <br />
		<div id="config" style="display:none;"></div>
    <?php } ?>
<br />
<div id="ga" style='width: 720px; height:500px;'></div><br /><br />
</div>
