<script type="text/javascript">
	$j(document).ready(function()
	{
		if(document.getElementById('content')) {
			CKEDITOR.replace( 'content' );
		}	
	});
</script>
<?php 

	$divs = $this->divs;
	$div_id = $this->div_id;

	if(!isset($div_id)) {
		
		echo "<div id='admin_dashboard' ><br /><br /><p><a href='/admin/newdiv'>New Div</a></p><br /><br />";
		foreach($divs as $div) {
		echo "<p><a href='/admin/divedit/?id=".$div->id."'>".$div->name."</a></p><br />";
		}
		echo "</div>";
	}
	else {

$_f = $this->divForm;
?>
<div class="page-head">
    <h3><?php echo str_replace("_"," ",$_f->getName()); ?></h3>
</div>
<br/>
<div class="negMargin">
        <form action="<?php echo $_f->getAction(); ?>"
                method="<?php echo $_f->getMethod(); ?>"
                id="form-validate"
        >
                <?php
                $groups = $_f->getDisplayGroups();
                foreach($groups as $group) {
                ?>
                        <fieldset class="fields regField <?php echo $group->getAttrib('class'); ?>">
                            <legend>
                                                <?php echo $group->getLegend(); ?>
                            </legend>
                                        
                                        <?php
                                        $elements = $group->getElements();
                                        foreach($elements as $element) { ?>
                                                        <?php echo $element->render(); ?>
                                        <div class="clear"></div>
                                        <?php
                                        }
                                        ?>
                        </fieldset>
            <?php
                }
                ?>
            <br/>
</form>
<?php }
?>
<?php 

if($backups = $this->backups) {
	if(count($backups->toArray()) > 0) {
		$url = 'http://'.Bootstrap::getConfig('site','url');
?>

<div id="restoreWrap">
	<h2>Restore from a backup:</h2><br />
	<p>The following backups are sorted with the most recent at the top. To restore simply click on the time and it will be automatically recovered.</p>
		
		<div id="backups_header">
			<ul>
				<li>I.D.</li>
				<li>Time</li>	
			</ul>
		</div>
		
		<?php foreach($backups as $item) { 
			  	$preview = strip_tags(str_replace(array("'",'"'),'',$item->backup_preview));
		?>
					<ul class="backup_item">
						<li class="backup_id"><a id='backups_<?=$item->id?>'><?=$item->id?></a></li>
						<li><a href="<?=$url?>/backup/preview/id/<?=$item->id?>"><?=date('g:i:s a - M j, Y',$item->backup_revision)?></a></li>
					</ul>
		<?php } 
	} 
} ?>
</div>
