<?php 

$pages = $this->pages;
$page_id = $this->page_id;

if(!isset($page_id)) {
?>
	<table class="tablesorter">
		<thead>
			<tr>
				<th>Page Code</th>
				<th>Page Name</th>
				<th>Page Title</th>
				<th>Actions</th>
			</tr>
		</thead>
		<?php foreach($pages as $page) { ?>
		<tr>
			<td><a href="/admin/pageedit/id/<?=$page->id?>" class="link"><?=$page->page_code?></a></td>
			<td><a href="/admin/pageedit/id/<?=$page->id?>" class="link"><?=$page->page_name?></a></td>
			<td><a href="/admin/pageedit/id/<?=$page->id?>" class="link"><?=$page->page_title?></a></td>
			<td><a href="/admin/pageedit/id/<?=$page->id?>" class="link">Edit Page</a></td>
		</tr>
		<?php } ?>
	</table>
	<?=$this->paginationControl($pages, 'Sliding', 'pagination.phtml')?>
	<div class="center">
		<a class="btn tab02b grey" href="/admin/newpage/">Add a Page</a>
	</div>
	<div class='clear'></div>
	<?php
}
else {

$_f = $this->pageForm;
?>

<div class="page-head">
	<h3><?php echo str_replace("_"," ",$_f->getName()); ?></h3>
</div>

<br />
	<form action="<?php echo $_f->getAction(); ?>"
		  method="<?php echo $_f->getMethod(); ?>"
		  id="form-validate"
	>
	<?php
	$groups = $_f->getDisplayGroups();
	foreach($groups as $group) {
	?>
		<fieldset class="<?php echo $group->getAttrib('class'); ?>">
			<legend><?php echo ucwords($group->getLegend()); ?></legend>
			<div section="<?=$group->getAttrib('id');?>">
				<?php
				$elements = $group->getElements();
				foreach($elements as $element) { ?>
				   <div section='<?=$element->getName()?>'>
		 			   <?php echo $element->render(); ?>
					   <div class="clear"></div>
				   </div>
				<?php } ?>
			</div>
		</fieldset>
	<?php }?>
	<br/>
	<div class='back_button' onclick='history.go(-1)'>Back</div>
	<div class="save_button" onclick="jQuery('form').submit()">Save</div>
		<div class="clear"></div>
</form>
<?php } ?>
