<?php $users = $this->users; ?>
<form id='form_validate' action='/admin/users/' method='get'>
	<div class="element">
		<label for='q' style="text-transform: initial;">Search for a user</label>
		<input id='q' name='q' type='text' value='<?=$this->q?>' />
	</div>
	<div class='search_button' onclick='$j("#form_validate").submit()'>&nbsp</div>
</form>
<table class="tablesorter">
	<thead>
		<tr>
			<th>Screen Name</th>
			<th>E-mail</th>
			<th>Name</th>
			<th>Position</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($users as $user) { ?>
		<tr id='admin_user' onclick="window.location.href='/user/edit/id/<?=$user->id?>'">
			<td><?=$user->user_screen_name?></td>
			<td><?=$user->user_email?></td>
			<td><?=$user->user_firstname?> <?=$user->user_lastname?></td>
			<td><?=$user->user_position?></td>
		</tr>
		<?php } ?>
	</tbody>
</table>
<?=$this->paginationControl($users, 'Sliding', 'pagination.phtml')?>
<div class='clear'></div>
<div class="center">
	<a class="btn tab02b grey" href="/user/add">Add User</a>
</div>
